### ISSUE TITLE
[feat] Option to let a userscript run upon page load via ajax

### ISSUE THREAD

**Issue by orionlee** [violentmonkey/violentmonkey#1028]
Normally, userscripts are run when a page is loaded. However, for single page applications (or sites that are partially like that), the model breaks down. Userscripts won't be run when an user navigates to the appropriate page, typically via some ajax call.

E.g., for github.com, I'd want to create a script to tweak Issues tab (https://github.com/violentmonkey/violentmonkey/issues),

A native way to do so is to create a script that matches the issues' URL. And it'd work when the browsers loads the page directly. However, it doesn't work when users navigates to the page from another tab, say, from Code tab to Issues tab. 

Currently, to address such cases, userscript developers could try different workarounds that might work for some cases, e.g., observing DOM changes (signaling ajax load), hacking `history` to observe changes, etc.

It'd be great if ViolentMonkey can reduce such burden. 

Thoughts?

---
A rough proposal:

Provide a new meta, say, `@runAtWebNavigation`. If a script has such meta, ViolentMonkey will try to inject the script when users navigates to another page (usually by ajax).
- From an end user's perspective, that usually means the URL is changed but there is no full loading of the new page.
- From an userscript developer perspective, he/she can largely write the script without worrying about ajax cases. [*]
- From a technical perspective, ViolentMonkey could possibly catch such events and inject scripts by using extension's [webNavigation API](https://developer.chrome.com/extensions/webNavigation).

[*] Some tweaks might still be needed but considerably easier, e.g., if the script changes a site's top-level header that remains unchanged after ajax-based navigation, it needs to ensure the changes aren't applied again.

**Comment by tophf** [comment]
To make it realistically useful this is something that all userscript engines should agree upon, mainly Tampermonkey as it's the most popular one. Historically, Violentmonkey didn't spearhead such developement.

I also don't think that running the entire script is good in such cases because this is not how SPA sites should be handled in general. Just because it'll be easier for clueless authors and for simple scripts doesn't make it right. This category of authors will never know about the fancy meta key anyway. Normally, only some part of the script needs re-running so a possible solution might be GM_addUrlChangeListener and GM_removeUrlChangeListener similar to GM_addValueChangeListener.

**Comment by tophf** [comment]
P.S. We won't be adding `webNavigation` permission just for this feature so we'll use `browser.tabs.onUpdated` instead.

**Comment by orionlee** [comment]
I made an issue here to see if there are any interests to address such use cases. 

Something like `GM_addUrlChangeListener` would work too. With tweaking github issues UI example, actual userscript codes would be something like:
```javascript
GM_addUrlChangeListener((event) => {
  if (location.pathname === '/violentmonkey/violentmonkey/issues') {
    tweakIssuesUI();
  }
});
```

**Comment by orionlee** [comment]
FYI, in one of my userscripts, I ended up implementing a variant of `GM_addUrlChangeListener`. 

https://github.com/orionlee/planet_hunters_tess_userscripts/blob/e08fdf542f25938fb7eeaa0f3e1c0daf289ecce7/zn_planet_hunter_tess.user.js#L52

In theory, the implementation might have performance issue for general usage, as it uses a `MutationObsever` to watch *all* the DOM changes. 

Empirically, it is sufficient for my use case, even for a page that changes its DOM quite a bit (users zooming / panning of a svg-based graph).

**Comment by gera2ld** [comment]
If I understand correctly, what you want is to apply scripts to SPAs, and you probably want to just write code in callbacks so that you don't have to worry about the navigation events.

Here are some reasons why I think this should not be supported in Violentmonkey:

1. The developer's work wouldn't be easier if he/she writes code in navigation callbacks.

   The developer has to be aware that the script runs in SPA because once the script executes, there is no way to revert, so it's the developer's job to do initializations exactly once, and do cleanups on navigations.

2. Violentmonkey can hardly provide such callbacks that work in all situations.
    AFAICT, SPAs navigate and update their URLs in different stages.

    For example, GitHub always changes its URL first, and then load data and update the view later, while some other sites (maybe those with react-router) load data first and keep the old URL until the view is refreshed.

    So even Violentmonkey provides a URL navigation callback, it does not promise anything. And I don't think Violentmonkey can decide when the view is ready for a script to tweak.

3. It's easy to make such a callback that works for a certain site, but hard to make one that works in all situations.

    Actually I also had similar issues to make a script work in a feature-rich SPA. I just hacked `history` API with less than 20 lines of code and everything worked like a charm.

So I prefer an out-of-the-box library that can be `@require`d and easily used in SPAs, providing something like `onURLChange`.

**Comment by tophf** [comment]
So, we'll implement this in any form only if it gets implemented in other userscript engines.

**Comment by orionlee** [comment]
- I agree that having callbacks on URL change won't necessarily solve the whole issue for all cases, as a SPA could do actual UI update after the URL change. But it'd still be easier.
- it sounds like you have a `history` hack that works for many cases. Could you share it? I attempted a `history` hack sometime back (to trap its `pushState`, for customizing github if I remember correctly). It didn't work - it seems as if the site got hold of original `history` object.

**Comment by tophf** [comment]
The userscript should have `@run-at document-start` for the history hack to be more reliable, otherwise the site may save a reference to the original prototype methods and use them directly. There's a also a problem of `content` mode or Greasemonkey4/Firemonkey which use Userscripts API, for which you need wrappedJSObject.

```js
const exportFunc = typeof exportFunction === 'function' ? exportFunction : (fn => fn)
const pageWindow = unsafeWindow.wrappedJSObject || unsafeWindow
const pageHistory = pageWindow.History.prototype
const origPush = exportFunc(pageHistory.pushState, pageWindow)
pageHistory.pushState = exportFunc(function () {
  origPush.apply(this, arguments)
  urlChange()
}, pageWindow)

const origRepl = exportFunc(pageHistory.replaceState, pageWindow)
pageHistory.replaceState = exportFunc(function () {
  origRepl.apply(this, arguments)
  urlChange()
}, pageWindow)
```

Note however, usually a dummy MutationObserver + url check is sufficient:

```js
let lastUrl;
new MutationObserver(() => {
  if (location.href !== lastUrl) {
    urlChange(lastUrl, location.href);
    lastUrl = location.href;
  }
}).observe(document, {subtree: true, childList: true})
```

**Comment by orionlee** [comment]
Thanks for the information! I probably didn't use `@run-at document-start` back then. 
I also found out recently that a dummy `MutationObserver` runs okay in practice, to my pleasant surprise.
