### ISSUE TITLE
[Feature-Request] Don't minify / uglify released extension versions

### ISSUE THREAD

**Issue by f6ADt** [violentmonkey/violentmonkey#1109]
Current release versions of Violentmonkey downloaded from addons.mozilla.org are getting minified. I propose to omit this build step and just deliver the extension unminified for privacy reasons and trust in the published source code.

Minifying makes sense for web applications to reduce the bundle size and increase performance. Though an installed browser extension does not need this build step - the code is already available locally.

(For those who would like to verify this: go to https://addons.mozilla.org/en-US/firefox/addon/violentmonkey and download the extension as `.xpi` and open with your archive manager of choice.)

Sad reality is: It is very easy to embed trackers in releases, while still being MIT licensed - I wouldn't state, this is the norm, but auditing certainly still remains necessary. 

To make it clear, I really like Violentmonkey as an open source alternative to Tampermonkey! It also seems to have more active development than Greasemonkey. After having researched a bit, I am willing to trust gera2ld (and other contributors) considering that user-script extensions in general are getting a multitude of permissions in the browser, which for nearly all of us is the most important and frequently used app.

Being a  privacy conscious user, I just would like to get an eye on the released source code. Uglifying/Minifying/obfuscating complicates auditing and is is not needed in my view.

**Comment by tophf** [comment]
No, it's not feasible and there'll be no benefits for anyone.

Without the minifying step of the build process the size of files will be approximately 10 times bigger than the original source because that's how WebPack compiles stuff. You can view the result when running `yarn dev`, see [README.md](https://github.com/violentmonkey/violentmonkey/blob/master/README.md).

> Though an installed browser extension does not need this build step - the code is already available locally.

No, it's needed because the much more pronounced benefit is the shorter compilation and parsing time in the JavaScript engine.

> Being a privacy conscious user, I just would like to get an eye on the released source code. Uglifying/Minifying/obfuscating complicates auditing and is is not needed in my view.

That's a common misconception whereas all you need is to build the source code and compare it to the released version, which is what AMO (addons.mozilla.org) reviewers do.

**Comment by f6ADt** [comment]
@tophf Thanks for the quick response, appreciate the feedback - I wasn't aware of the apparent bigger difference in performance. Building the source code and diffing it to the `.xpi` sounds like a very reasonable approach.

**Comment by GIPeon** [comment]
Hey I guess thank you for this nice explanation, may I suggest to sticky this somewhere or put it in a FAQ in the readme or something?
Also this link may be of help for enhanced transparency
https://extensionworkshop.com/documentation/publish/source-code-submission/
Thank you for this extension!

**Comment by tophf** [comment]
The link for source code submission describes what the extension author is already doing when submitting a new version to addons.mozilla.org so adding it to readme won't be helpful to anyone else. Anyway, it's up to @gera2ld to decide. Maybe a small explanation won't hurt, IDK.

**Comment by gera2ld** [comment]
Added a question to FAQ: https://violentmonkey.github.io/faq/#why-is-the-release-minified

**Comment by GIPeon** [comment]
Very good explanation post, thank you! 👏

**Comment by Crystal-RainSlide** [comment]
Will this be helpful?

- https://reproducible-builds.org/
- https://en.wikipedia.org/wiki/Reproducible_builds

**Comment by phil294** [comment]
> Without the minifying step of the build process the size of files will be approximately 10 times bigger than the original source because that's how WebPack compiles stuff. You can view the result when running yarn dev, see README.md.

I measured it, all source file JS files weigh 196.1 KiB in total unmodified. Surely not an argument?

> No, it's needed because the much more pronounced benefit is the shorter compilation and parsing time in the JavaScript engine.

Are you referring to Vue files being compiled into render functions? While that is true, that only refers to the interface, so I don't really see your point. The stripping of logging output surely also does not require minification? For everything else, I'd be very surprised if there is any measurable performance boost by running Webpack et al (?)

> No, it's not feasible and there'll be no benefits for anyone.

That's just not true, let alone because what is already specified at the top of https://violentmonkey.github.io/posts/violentmonkey-workflows/. Minified code in a web extension (something that can and will access *everything*, for good or bad. Remeber the Stylish malware thing 4 years ago?) always conveys the feeling there is something shady going on. For example, before installing any extension, I quickly skim trough the xpi file to see what it does. This is much quicker than cloning and building the source locally (which always works differently, pulls 3rd party stuff on your computer and so on) and comparing the minified code.

It is a good thing AMO does review extensions though, if that gives you reason enough to trust it. However, it appears to be half automated. Also, remember Stylish?

> Since we are in 2020s, this question should not be asked by a web developer. If you have employed such a guy, trust me, he/she should be fired.

How is this helpful?

> Code obfuscation usually encodes the minified code to make it harder to read [...] we have never included such tools in our project.

No one's going to bother reading stuff like `for(var o in e)n.d(r,o,(t=>e[t]).bind(null,o));return r},n.n=e=>{var t=e&&e.__esModule?()=>e.default` anyway, it already comes pretty close to obfuscation. As a middle ground, I think it would be best to disable most feature of webpack terser, such as mangling or compression.

**Comment by tophf** [comment]
1. You've measured something else. All compiled js from webpack without sourcemaps is 3MB with vendor libs like codemirror, out of which 1.6MB is our code. The minified js is 0.9MB overall, 0.4MB ours.

2. Minified code is loaded/parsed/compiled/executed by the browser noticeably faster, which is a fact that you can see yourself by profiling the page load process. We try to make Violentmonkey as lightweight as possible in order not to slow down the page load process, so every millisecond counts.

3. Quick perusal of the code won't guarantee safety, it just gives you a false sense of security, which is just as bad as blind trust or maybe even worse.

4. Web developers have been using minification in all web sites for the past decade, which is why wondering about it is weird.

This topic was discussed a lot in many places, so I don't want it to go in circles here forever as well, which is why I'm locking the issue.
