### ISSUE TITLE
When is the new release?

### ISSUE THREAD

**Issue by sn260591** [violentmonkey/violentmonkey#1112]

**Comment by gera2ld** [comment]
For Chrome:
The beta version was submitted to CWS and requires an in-depth review as told by CWS. So it may take some time.
After the beta version is released and bugs are fixed, say two more weeks, we will update the stable release and wait for another in-depth review.

For Firefox:
The stable release is the same as Chrome, maybe earlier to be public because no in-depth review is required.
A beta version should be available soon as self hosted.

**Comment by idgas01** [comment]
Thank you for the new release 2.12.8.  I haven't tested it yet, but at first glance it seems to be an improvement and word-wrap seems to work again.  I've been waiting for this update a long time.  I was using 2.12.4 to get word-wrap to work.  It looks very nice.  Thank you for all your hard work!  Have a great Christmas and New Year's!
