### ISSUE TITLE
4YI: A bug in Firefox WebExtensions content scripts environment affecting VM

### ISSUE THREAD

**Issue by KOLANICH** [violentmonkey/violentmonkey#1124]
### How to reproduce it?
1. install a userscript from https://gist.github.com/KOLANICH/5c85e09af65d87b24a3763c1316f099e
2. open any page
3. see browser console

### What is the expected result?
`after` message is printed.

### What is the actual result?
It is not. `TextEncoder` in content_scripts environment returns typed arrays (and their buffers) that seem to belong to another context.

### Environment
- Browser: Firefox
- Browser version: Developers Edition
- Violentmonkey version: any
- OS: any

**Comment by tophf** [comment]
Can't reproduce in stable Firefox or Nightly using VM stable or beta.

**Comment by tophf** [comment]
Ah, the report lacks the most important detail: Violentmonkey must be manually configured to inject in `content` mode or the script should be edited with `@inject-into content`. So far this looks like a problem of Firefox's implementation of content script sandbox, so I doubt we can do anything about it but I'll try to investigate...

**Comment by tophf** [comment]
The global browser console shows `Error: Permission denied to access object` when "show content messages" option is enabled in its prefs. This error message is wrong because all parts of the code belong to the same context so this is definitely a Firefox bug and I don't see how we can circumvent it.

**Comment by KOLANICH** [comment]
>Ah, the report lacks the most important detail: Violentmonkey must be manually configured to inject in content mode 

I haven't configured it this way, I just installed it from AMO. In fact I usually use GreaseMonkey, just checked that it reproduces in VM too. I know that it is a [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1681809) since I have created a webext to verify that, I have posted here so that if any of VM users encountered it he would get the details.

**Comment by tophf** [comment]
I guess the URL you've tried it on was forbidden for injection by Firefox which is why Violentmonkey switched to `content` mode. This is really really rare.

**Comment by KOLANICH** [comment]
No, as you see the script by the link matches all the HTTPS URIs. I have tested on different websites, including GitHub, Google and Wikipedia. With the same result.

**Comment by KOLANICH** [comment]
BTW: I use NoScript with JS disabled for the most of websites.

**Comment by tophf** [comment]
Well, since the problem exists only in `content` mode it means that something has enabled this mode. It can be done in VM settings or it can happen automatically if the site forbids creating DOM script elements which can happen on sites with paranoid CSP or due to another extension. So this problem is really rare normally.

**Comment by KOLANICH** [comment]
Yeah, NoScript utilizes CSP to kill inline scripts (and it is bad, since it has been bypassed by websites many times. Including tryes to attack users of Tor. IMHO it is a backdoor in NoScript and TorBrowser).


>creating DOM script elements
>So this problem is really rare normally.

Do you mean that `GM.` API is injected by VM into websites, visible to scripts in pages (or at least the injected DOM elements are visible and can be used for fingerprinting?), and can be used by webpages scripts to bypass security features?

**Comment by tophf** [comment]
> Do you mean that GM API is injected by VM into websites

The sandbox code is injected into the page in the default injection mode but I haven't seen a way for a site to take advantage of it because we inject before the page scripts can install any hooks. The script elements are removed at once so there are no tracks. One exception would be the moment Violentmonkey is installed/updated in Firefox because Firefox runs content scripts at this moment. If we ever see evidence that the latter is abused in the wild we'll simply add a check to skip injection in this case altogether.

**Comment by KOLANICH** [comment]
Thank you for the info.
