### ISSUE TITLE
Tabs created by dragged userscript files do not close

### ISSUE THREAD

**Issue by KLaurence** [violentmonkey/violentmonkey#1129]
### What is the problem?
Tabs that the browser creates when a .user.js (userscript) file is dragged into it do not close.

### How to reproduce it?
1. Drag a .user.js file into the browser.

### What is the expected result?
The tab created by dragging the .user.js file closes.

### What is the actual result?
The tab created by dragging the .user.js file doesn't close. The 'Installing script' dialog opens in another tab.

### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?
The same as above. The latest release (v2.12.8) is being used.

### Environment
- Browser: Firefox
- Browser version: 83.0
- Violentmonkey version: v2.12.8
- OS: Windows

**Comment by tophf** [comment]
This is intended because there's no other way in Firefox to track changes to a local file otherwise when the corresponding option is enabled in the installation dialog:

![image](https://user-images.githubusercontent.com/1310400/102319200-8c31a580-3f8b-11eb-8b53-d49ef81827b9.png)

I guess we can auto-close the original tab when the install dialog is closed...

**Comment by KLaurence** [comment]
I see. Do you think there should be documentation about this, in the extension or somewhere else?

**Comment by tophf** [comment]
Maybe we'll add it if people keep asking about this.
