### ISSUE TITLE
(Suggestion) Offer an option to `Update disabled scripts`

### ISSUE THREAD

**Issue by darkred** [violentmonkey/violentmonkey#1134]
My suggestion is to offer an option to `Update disabled scripts`.

This feature can be useful for scripts that you keep them disabled for some reason (because e.g. they no longer work and need to be fixed by their author), instead of uninstalling them.
Then, by looking in the dashboard (sort by last updated), if you see that such script has got updated, you might want to try it again.

Thank you

**Comment by tophf** [comment]
Violentmonkey already updates disabled scripts so this option isn't necessary.

**Comment by darkred** [comment]
I'm glad! Thanks.

&nbsp;

But, do you think that having this as a separate option would be useful to those that want the opposite?
I have this issue in mind this old Greasemonkey issue https://github.com/greasemonkey/greasemonkey/issues/1480 of which a very experienced script author and OUJS owner said that it considers such behavior a bug:

> I've been able to confirm this bug on several occasions myself. Even if a script is disabled, the script is checked for an update and if one is found it installs. Disabled scripts should never be checked for updates automatically.

**Comment by tophf** [comment]
Sounds like an opinion. Mine is we don't need neither this option nor its opposite.

**Comment by tophf** [comment]
On the other hand implementing this option would be trivial so I don't mind adding it if @gera2ld agrees.

**Comment by gera2ld** [comment]
I agree with arantius's opinion. I don't see any reason why we need to skip update checking for disabled scripts since this is obviously not security related.

Anyway we may add it when someone really needs this feature asks for it, hopefully with a good reason.

Considering security, we should not auto update any script installed via HTTP, no matter whether it's disabled. But this should be another issue I guess.
