### ISSUE TITLE
升级2.12.8后脚本失效…

### ISSUE THREAD

**Issue by Itzamana** [violentmonkey/violentmonkey#1140]
失效脚本：https://github.com/rafaelgomesxyz/esgst
浏览器：Chrome 87.0.4280.88 64位

升级2.12.8之前还能用来着…

**Comment by tophf** [comment]
Two problems here:

1. our detection is outdated so it misses the [official script link](https://github.com/rafaelgssa/esgst/releases/latest/download/userscript.user.js) - same behavior in 2.12.7 and earlier versions
2. the script is using JQueryUI - same as #1138 - already fixed in [2.12.9](https://github.com/violentmonkey/violentmonkey/releases)

**Comment by Itzamana** [comment]
明白了，感谢回复！
