### ISSUE TITLE
Can leak incognito data

### ISSUE THREAD

**Issue by brian6932** [violentmonkey/violentmonkey#1167]
Now this only occurs with Super Preloader enabled, but I think a UserScripts manager should block this either way

Bug Report here: https://github.com/machsix/Super-preloader/issues/485

**Comment by tophf** [comment]
The problem I guess is GM_xmlhttpRequest used by that script. In which case it's not that straightforward. Violentmonkey can't just block it blindly because userscripts may need to reuse the main profile cookies/credentials. We could probably add a global option and a per-script option "Make network requests anonymously in incognito mode"...

**Comment by machsix** [comment]
You may want to see my comments here https://github.com/machsix/Super-preloader/issues/485#issuecomment-761526724

In summary, as long as you use the latest VM and browser, the XHR is sent without cookie specified in header. I indeed add `withCredentials = true` but it shouldn't do anything (I guess?) https://github.com/violentmonkey/violentmonkey/blob/e03e28b29a63d6790a24f5924f8419cf89e5b620/src/injected/web/requests.js#L139-L143

I tested with Firefox+VM and didn't see leakage. Maybe something related to Chrome?

**Comment by tophf** [comment]
Chrome and Firefox behave differently in regards to sending cookies via XMLHttpRequest. Chrome sends them by default because its implementation of XHR for extensions makes cross-origin URLs use the `same-origin` mode. Firefox doesn't send cookies by default which is why we have [custom code to send them](https://github.com/violentmonkey/violentmonkey/blob/e03e28b29a63d6790a24f5924f8419cf89e5b620/src/background/utils/requests.js#L256). So this is indeed browser-specific and we should probably add a workaround to remove the difference.

**Comment by AlttiRi** [comment]
_For Chrome._ _([In Firefox it is not available](https://bugzilla.mozilla.org/show_bug.cgi?id=1380812))_
You can just modify `manifest.json` by adding one line `"incognito": "split"` _(don't forget the comma `,`)_.
(It requires to install the unpacked version of this extension with enabled the developer mode)
See: https://github.com/violentmonkey/violentmonkey/issues/1086

**Comment by brian6932** [comment]
@AlttiRi's suggestion seems to work for me
