### ISSUE TITLE
Chrome IncognitoWindow Unable to Edit Scripts

### ISSUE THREAD

**Issue by gitti0** [violentmonkey/violentmonkey#1190]
### What is the problem?
I am unable to edit scripts, when i opened the ViolentMonkey dashboard and click on the icon to edit the user script.
### How to reproduce it?
1. Open Chrome with incognito window and open any page (e.g. google.com);
2. Open ViolentMonkey dashboard and click on the icon to edit the script.

### What is the expected result?
I should be able to edit the scripts in this scenario.
### What is the actual result?
Nothing is happening and no further windows are opening.
### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?
I found the bug in v2.12.9 and the latest beta v2.12.9.4
The behavaiour is not present in older versions of ViolentMonkey.

### Environment
- Browser: Chrome
- Browser version: 87.0.4280.141
- Violentmonkey version: 2.19.2
- OS: Windows 10

![vm_chr_inc_v1](https://user-images.githubusercontent.com/72917708/107351770-e8fc9880-6ac2-11eb-88aa-c724416af33f.jpg)

**Comment by tophf** [comment]
Until the fix is released in the new beta please use a workaround: open Violentmonkey dashboard in normal non-incognito window, then edit the script.

@gera2ld, is it too soon to make a new beta release, what's your view on this? There was nothing critical since the last beta, but if you're okay with a frequent release schedule, why not go for it.

**Comment by gera2ld** [comment]
Yeah I'll make a beta release for it. We can make beta releases nightly but maybe the CWS reviewers cannot keep up.
