### ISSUE TITLE
feature request: support @grant window.focus window.onurlchange and so on.

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#1195]
- [ ] window.focus
- [ ] window.onurlchange

Tampermonkey supports them https://www.tampermonkey.net/documentation.php#_grant

Vionlentmonkey support window.close now but not in wiki.

**Comment by tophf** [comment]
* `window.focus` already works so we don't need to explicitly support it.
* `window.onurlchange` sounds like a good idea, we can implement it

**Comment by ivysrono** [comment]
Is the following incorrect usage? 
```
// ==UserScript==
// @name        ! windowFocus test
// @namespace   Violentmonkey Scripts
// @match       https://cn.bing.com/
// @grant       window.focus
// @version     1.0
// @author      -
// ==/UserScript==

setInterval(() => {
  window.focus();
  console.log('focus');
}, 1000);
```

**Comment by tophf** [comment]
The code is fine but like I said there's no need to specify `@grant window.focus` since it already works.

**Comment by tophf** [comment]
Hmm, it seems that it works only when invoked from an event generated by the actual physical user. I guess then we can support `@grant window.focus` to allow scripts ignore this restriction.

**Comment by tophf** [comment]
As for `window.onurlchange` we won't implement it now because to make it work properly (also inside frames) we would have to add `webNavigation` permission, which will disable the extension in Firefox on update (we could make it optional but this is too much complexity for such a trivial thing). You can write a polyfill by overriding pushState and replaceState in `unsafeWindow` and listening to `popstate` and `hashchange` event - I guess there may be some existing libraries for that, as it's a well-known approach.

**Comment by gera2ld** [comment]
Maybe we can provide a library with `onUrlChange` callback or similar stuff as a general solution rather than implement such an API in such a hard way.
Besides, I don't think it's a good idea to ask for more permissions just to provide an API that can be easily mocked in pure JavaScript.

**Comment by tophf** [comment]
Okay, that's it then for now.
