### ISSUE TITLE
Provide an API to use chrome.tabs.insertCSS

### ISSUE THREAD

**Issue by ghost** [violentmonkey/violentmonkey#1226]
Currently `GM_addStyle` creates a `<style>` tag and attaches it to websites' DOM. An additional API to use `chrome.tabs.insertCSS` by providing a css string and an optional `cssOrigin` value would be useful. Currently there is no way from userscript to inject a user stylesheet.

**Comment by tophf** [comment]
Userscripts as a concept was created decades ago so in Violentmonkey we don't like extending it unless the proposed feature is already widely used by scripts for another userscript engine (most often Tampermonkey) and/or cannot be reimplemented via a polyfill. While this feature cannot be polyfilled, its extremely rare e.g. just a few userscripts would use it for a few sites. This is something that should be implemented as a separate specialized extension, maybe it already exists. Pinging @gera2ld to confirm.

**Comment by ab-c-d** [comment]
> it's extremely rare e.g. just a few userscripts would use it for a few sites. 

If it cannot be polyfilled, how could there be even 'a few' of them using the feature today?  I can imagine that once it is implemented, many userscript authors will begin to use it. I suggest to implement it as an additional argument to `GM_addStyle`. For example, 

```
GM_addStyle(css:string, cssOrigin?:string)
```
or 
```
GM_addStyle(css:string, options?: { cssOrigin: string})
```
Then any userscript that uses this API will keep working for e.g. Tampermonkey, unless they do some weird things like checking `arguments` object.

> This is something that should be implemented as a separate specialized extension

Only if the a purpose of a userscript is to inject some CSS.

**Comment by tophf** [comment]
>how could there be even 'a few' of them using the feature today? 

Extensions have been able to use it for ~10 years. And only a handful of them change the origin and only in rare cases where the site had `!important` inside an inline style attribute, which is extremely rare on the web. Try convincing Tampermonkey author and wait for the feature to gain traction. If we see more than a handful of userscripts and some sensible usage examples it'll increase the chance of us implementing it. So far I see none, but let's wait for gera2ld...

**Comment by ab-c-d** [comment]
> Extensions have been able to use it for 10 several years since it was implemented. 

I see you've edited your original post so that it now takes account of extensions, not only userscripts, good job.

It seems that you are so certain that only a few extensions use the origin property, do you have a statistics? My experience tells otherwise.

> Try convincing Tampermonkey author
If your goal is to faithfully copy the behavior of Tampermonkey, good luck with that. Then I don't see much reason to tell my users to use this instead of Tampermonkey. It looks really absurd that you are telling it as if it is adding a whole new concept to the userscript, while it is simply a matter of adding an optional argument to an existing API. Maybe you simply don't want to code, I guess.

**Comment by tophf** [comment]
> I see you've edited your original post so that it now takes account of extensions, not only userscripts, good job.

That was what I meant originally so I just clarified it as you seemed to be salty.

> It seems that you are so certain that only a few extensions use the origin property, do you have a statistics? 

I don't have the statistics but I know that the cssOrigin option was added for precisely two cases: to override `!important` in selectors that have the same specificity and to override `!important` in an inline style attribute. The former can be more or less trivially implemented via the standard author style by using specificity hacks so it doesn't necessitate extending GM_addStyle, but for the latter there's no workaround. Still, the second use case is extremely rare on the web: in my 15 years of experience in web dev I've mostly seen it being used in advertisements on badly designed sites.

> If your goal is to faithfully copy the behavior of Tampermonkey, good luck with that.

Our goal is to be compatible and avoid fragmenting the common userscripts API.

> It looks really absurd that you are telling it as if it is adding a whole new concept to the userscript, while it is simply a matter of adding an optional argument to an existing API.

Changing behavior of an established API is not a simple matter because it fragments the common userscripts API.

> Maybe you simply don't want to code, I guess.

I don't know where you communicate usually but we don't tolerate such passive-aggressive tone so I'm locking the issue.

**Comment by tophf** [comment]
To clarify, it's not like I'm against this feature per se, I see its usefulness even if it's limited, but I would like it to be implemented in a coordinated fashion by other userscript managers or at least by Tampermonkey, which is the de facto standard.

**Comment by gera2ld** [comment]
I'm not against this feature either. We may consider it if it appears to be useful to more users. Personally I never need such features in my scripts.

We are trying to support standard APIs or at least APIs that considered useful to a lot of users. We don't add features just because they are easy to implement. It's even easier to just expose all extension APIs.
