### ISSUE TITLE
v2.12.8以上版本更新脚本时出现“获取资源发生错误”

### ISSUE THREAD

**Issue by kidzgy** [violentmonkey/violentmonkey#1231]
### What is the problem?
更新部分脚本时，右下角会弹出“获取资源发生错误”的更新提示
### How to reproduce it?
1.比如安装这个脚本，然后再从暴力猴界面更新它，就会出现提示，一般情况下，带有// @icon  的语句，都会出现这种错误。如图：https://upload.cc/i1/2021/03/20/ogHtY4.png

2.
3.

### Environment
- Browser:Firefox
- Browser version:86.0
- Violentmonkey version:v2.12.12
- OS:Win10 x64

**Comment by gera2ld** [comment]
一般来说是网络问题，请自己解决。
也可以提供一个脚本链接我测试一下。

**Comment by kidzgy** [comment]
https://bbs.kafan.cn/thread-2204849-1-1.html
并不是网络问题，别人同样遇到这样的问题。
回滚到2.12.7版本就正常。
比如这样的脚本可以你测试一下：
https://greasyfork.org/zh-CN/scripts/10571
https://greasyfork.org/zh-CN/scripts/4233

**Comment by gera2ld** [comment]
我目前无法重现这个问题，而且测试了下图里的地址，确实是访问不通的。
大概错误一直是存在的，只是以前不提示，现在会提示了，刚确认了一下，错误提示是 2.12.8 加入的。

**Comment by gera2ld** [comment]
这个问题在 v2.12.11.1 beta 版中已经优化了，有兴趣的话可以测试一下（[传送门](https://violentmonkey.github.io/get-it/#beta-release)），注意备份数据。

Closing as duplicate of #1228

**Comment by tophf** [comment]
The first error is caused by an old format of screenshots which is no longer supported by GreasyFork, `https://greasyfork.org/zh-CN/scripts/380705/script.user.js` from the screenshot doesn't exist on GreasyFork (the script was deleted), same for id 394637. The icon from addons.mozilla.site, might be a genuine network error because the icon URL is valid.

@gera2ld I wonder if we should hide the error notification in case "notify updates" option is disabled?

**Comment by gera2ld** [comment]
> I wonder if we should hide the error notification in case "notify updates" option is disabled?

I agree. I guess this is already done in v2.12.11.1?

**Comment by tophf** [comment]
Currently the errors don't check `canNotify`.
