### ISSUE TITLE
Sharing getValues/setValues database between userscripts that works on different sites

### ISSUE THREAD

**Issue by alfa-th** [violentmonkey/violentmonkey#1251]
Lets say that i have userscript 1 that works on site A and userscript 2 that works on site B. 
Is it possible between userscript 1 and userscript 2 to share getValues/setValues database? 
Sorry if its a duplicate issue, i cant seem to find any issue with the search query of "sharing value", "global set value", "global get value", "global localStorage", and stuff

**Comment by tophf** [comment]
It depends on how the second site is opened.

In the simplest case your script A uses window.open to open site B so then it can use [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) directly.

Otherwise you'll need to add `@match` to both scripts so each one runs on both sites A and B. Then you can use a [custom event](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent) like `foo123` to send messages with data between the two script running on one site A. And if you want for script one on site A to communicate to script two on site B then you can use GM_addValueChangeListener.

For further assistance you can ask a question on stackoverflow.com or open a [discussion](https://github.com/violentmonkey/violentmonkey/discussions) here.
