### ISSUE TITLE
Can't create new userscripts

### ISSUE THREAD

**Issue by kevinsimper** [violentmonkey/violentmonkey#1264]
The buttons to "Save" and "Save and close" is disabled.

Found this error in the developer console.

```
vue.js:1 TypeError: Cannot read property 'name' of undefined
    at p (common.js:1)
    at a.scriptName (index.js:1)
    at un.get (vue.js:1)
    at un.evaluate (vue.js:1)
    at a.scriptName (vue.js:1)
    at a.<anonymous> (index.js:1)
    at a.t._render (vue.js:1)
    at a.r (vue.js:1)
    at un.get (vue.js:1)
    at new un (vue.js:1)
Ht @ vue.js:1
vue.js:1 TypeError: Cannot read property 'expandKeyMap' of undefined
    at a.mounted (index.js:1)
Ht @ vue.js:1
```

**Comment by tophf** [comment]
I can't reproduce the problem.

**Comment by kevinsimper** [comment]
Violentmonkeyv2.12.13

![2021-04-27 16 54 00](https://user-images.githubusercontent.com/1126497/116262939-3eb71780-a779-11eb-9178-5428b190fbf2.gif)

**Comment by tophf** [comment]
Ah, it was already fixed recently, the current version is 14 but it's not in Chrome's web store because they rejected the update with a nonsensical reason, CWS is notorious for such things. We don't know when the new version will be approved so meanwhile you can use [it](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.12.14) in unpacked mode.

**Comment by gera2ld** [comment]
It took some time for them to accept 2.12.13. Now 2.12.14 is submitted but may take another few days.
FYI [the BETA version](https://chrome.google.com/webstore/detail/violentmonkey-beta/opokoaglpekkimldnlggpoagmjegichg) should work.

**Comment by gera2ld** [comment]
2.12.14 has been published in CWS.
