### ISSUE TITLE
[Request] Force Update

### ISSUE THREAD

**Issue by TimidScript** [violentmonkey/violentmonkey#1295]
### What is the problem?
Using local server for updating script that I am writting, but the "Check for updates" button is not available due to I think a timeout.

### How to reproduce it?
1. Just update/install the script and try to update it again from the "Check for updates" button.

### Request
A way to force update whenever you want, even when versions match. So if I update the script using a third party editor and it is shared through my local server, I should be able to force an update.

Maybe also a setting to tell the script to update from the menu icon rather than going to the main settings window to access "Check for updates" button.

**Comment by tophf** [comment]
Violentmonkey handles local development differently, please see https://violentmonkey.github.io/posts/how-to-edit-scripts-with-your-favorite-editor/

**Comment by TimidScript** [comment]
I tried that but it never seems to work for me. Not sure why.

**Comment by tophf** [comment]
We would need more info from you in order to help like the browser, version, maybe a screenshot, what's in the console, and so on. Do you see "Script updated.[07:33:02]" after confirming the installer?

![image](https://user-images.githubusercontent.com/1310400/123641395-e3fa7480-d82a-11eb-8395-771c02b60e88.png)

**Comment by TimidScript** [comment]
Its working now, not sure why I couldn't get it to work last night.

Thank you.
