### ISSUE TITLE
Please, help with js script

### ISSUE THREAD

**Issue by EstherMoellman** [violentmonkey/violentmonkey#1296]
Hi,

This [YouTube ad blocker script](https://greasyfork.org/en/scripts/32626-disable-youtube-video-ads) works 100% perfectly at TamperMonkey.
With TamperMonkey there are no YT static ad images, no ads at all, when YT page loads the clean video image appears directly - no delays.

Unfortunately, this script is not fully working at ViolentMonkey: 75% of the time a YT static ad image appears before video starting. When the "play" button is pressed, no ads, and video starts directly. The YT static ad image is my problem!

I'm using latest Firefox Nightly.
Please, can you help me?

Thank you in advance!

**Comment by tophf** [comment]
We don't debug scripts because it's only their authors know how the various parts of their code should behave whereas it would generally take an inordinate amount of time for us to reverse-engineer all that. As an exception though I've tried running this script and I saw a mistake in the code at line 294: `c` variable is not defined anywhere. Please contact the author of the script.

**Comment by EstherMoellman** [comment]
Hi @tophf , I understand you.

But please, don't miss the main point of my issue: This YouTube ad blocker script is 100% perfectly working with TamperMonkey!
It doesn't matter whether the script has "bad syntax"... again, this script 100% works with TamperMonkey... and it's not working with ViolentMonkey... THAT'S THE POINT! : )

Hopefully someone can help me get this script working with ViolentMonkey.

Thank you anyway!

**Comment by tophf** [comment]
There's a lot of scripts around that behave differently in Violentmonkey/Tampermonkey/Greasemonkey due to the inherent differences in their approach for injection of scripts. It's the responsibility of a userscript's author to debug the script and find the reason, then report it to us and the other affected userscript managers.

**Comment by tophf** [comment]
Open a new topic in [discussions](https://github.com/violentmonkey/violentmonkey/discussions), which exists for user-to-user communication and support so maybe someone else would help.
