### ISSUE TITLE
FF manifest error

### ISSUE THREAD

**Issue by 514guy** [violentmonkey/violentmonkey#1303]
Not critical, but the manifest.json file has FF complaining that:
`Reading manifest: Error processing permissions.9: Value "declarativeContent" must either: must either [be one of ["clipboardRead", "clipboardWrite", "geolocation", "idle", "notifications"], must either [be one of ["<all_urls>"], match the pattern /^(https?|wss?|file|ftp|\*):\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$/, or match the pattern /^file:\/\/\/.*$/], be one of ["bookmarks"], be one of ["history"], be one of ["activeTab", "tabs"], be one of ["cookies"], be one of ["topSites"], be one of ["webNavigation"], or be one of ["webRequest", "webRequestBlocking"]], be one of ["alarms", "storage", "unlimitedStorage"], be one of ["browsingData"], be one of ["menus", "contextMenus"], be one of ["geckoProfiler"], be one of ["sessions"], be one of ["browserSettings"], be one of ["contextualIdentities"], be one of ["dns"], be one of ["downloads", "downloads.open", "downloads.shelf"], be one of ["management"], be one of ["privacy"], be one of ["proxy"], be one of ["nativeMessaging"], be one of ["theme"], be one of ["identity"], or match the pattern /^experiments(\.\w+)+$/`
Noticed on Waterfox Classic (FF 56.2-based), W10 Ent 20H2, with 2.13 beta.

**Comment by tophf** [comment]
It's a Chrome-only permission, which Firefox simply ignores so there's no problem. Theoretically we can change the manifest on-the-fly when building xpi to remove this value and also remove `browser_specific_settings` from Chromium zip, WDYT, @gera2ld?

**Comment by gera2ld** [comment]
I think it's confusing to maintain a few packages when they are almost the same and there could be one package working on different platforms. They are all just zip files, and they get their signatures and browser-specific extensions only after being submitted to stores. In that case users may be confused about which one to choose (if they want to choose an unsigned version for whatever use), and the maintainer (me) may submit wrong packages to stores.

I don't see much benefit on this, just to get rid of a warning message that is displayed for debugging?

I'm OK with this if the process from packaging to publication can be automated. But if we have to maintain and choose the zip files manually, why not just keep it simple and ignore the warnings?

p.s. I think this can be added to FAQ since it has been asked several times.
