### ISSUE TITLE
Missing scripts

### ISSUE THREAD

**Issue by John-Gee** [violentmonkey/violentmonkey#1311]
### What is the problem?
Hello,

Some of my scripts disappeared around today.
Unlike in #1048 and co I did not lose them all, but maybe 3, 2 local and 1 from Greasy Fork.

I was not using sync before so it's unlikely related to that.

Like @tophf wrote in the above bug, I too have a daily backup of my home folder, so it should not be a major issue to me, except I cannot find what file/folder to overwrite with my backup. I've tried the ones in Local Extension Settings, Extension and IndexedDB with no luck. When I remove the first and last folders, nothing seems to change, even after extension reload (should I restart the browser as well?), when I remove the folder in Extension, well it breaks the extension but overwriting it with my backup from yesterday seems to do no good.

### How to reproduce it?
No idea, the browser did not crash/restart, I just stopped using it, came back to it hours later and the effects of some scripts were gone so I looked and saw them missing. 
### What is the expected result?
Not lose the extensions
### What is the actual result?
Lose some extensions.

### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?
Likely too late for that.

### Environment
- Browser: Chromium
- Browser version: 91.0.4472.114
- Violentmonkey version: 2.13.0
- OS: Arch Linux

Thank you!

**Comment by tophf** [comment]
GreasyFork often deletes scripts that violates their Terms of Service or the license of another script.

**Comment by tophf** [comment]
As for the main problem, the only case when Violentmonkey can delete a script by itself is when the script was already deleted and was in the Recycle Bin. If it wasn't then this all sounds like a bug in the browser. Without sync enabled I don't see any possibility for a script to disappear by itself because that part of the code simply doesn't run. So, unfortunately, there's nothing we can do here.

**Comment by John-Gee** [comment]
I don't believe I put anything in the Bin, but it could definitely be a bug in the browser.

Can you at least tell me what file to pull for my backup? I don't want to rewrite my local scripts. :)

Thank you!

**Comment by tophf** [comment]
There are tutorials on dealing with extension storage files in a Chrome profile. In short you can simply restore all directories that have the extension id in it, which is shown when you open the dashboard: `jinjaccalgkegednnccohejagnlnfdag`. Violentmonkey's storage should be inside `Local Extension Settings`. Make sure you exit Chrome first using the Exit command in the menu so that no hidden processes remain.

**Comment by John-Gee** [comment]
Yup as written in my op those are the ones I overwrote, but I did not restart the browser so maybe that's the problem. I'll try and report back, and then close this.

Thank you!

**Comment by John-Gee** [comment]
Finally got to trying, the Local Extension Settings folder was different, but I still don't see my scripts back. I've gone a little back and forth and you are right that I need to do that without the browser running, if not there's some sort of cache that prevents any change from affecting it.

Anyway, I am not sure what happened, but I guess no point in spending too much more time no this so I'll close.

Thanks!
