### ISSUE TITLE
GM_download behavior incorrect in Microsoft Edge

### ISSUE THREAD

**Issue by Invertex** [violentmonkey/violentmonkey#1333]
### What is the problem?
When initiating a GM_download, there is no Save-as popup for the user to choose location, but there is when users manually do a Save-As.

### How to reproduce it?
1. Use ViolentMonkey in Edge.
2. Initiate a download for an image using a `GM_download` call.

### What is the expected result?
For the user to be prompted where to save the file, just like when they manually click to Save-As, no matter the browser.

### What is the actual result?
Instead it shows up in the Downloads menu with a button to bring up the Save-As menu.
 
### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?
Same.

### Environment
- Browser: Edge
- Browser version: 92.0.902.67 (Official build) (64-bit)
- Violentmonkey version: 2.13.0/2.13.0.2
- OS: Windows 10 64bit

**Comment by tophf** [comment]
Works for me in the same setup. Can't investigate further without 1) a demo script and 2) a screen recording that demonstrates the exact sequence of actions.

**Comment by Invertex** [comment]
It happens in my Twitter enhancement script so you could test it that way:
https://github.com/Invertex/Twitter-AutoHD

Just visit Twitter and try right-click Save As on a post image and it will download the image using GM_download()

**Comment by tophf** [comment]
I guess you didn't enable the option in browser settings to prompt saving for each download. Unless this option is enabled we can't force the dialog currently.

We would have to add the `downloads` permission to Violentmonkey but it will disable the extension on the next upgrade so many users will be baffled by the security prompt saying that our extension wants to "manage downloads" and they won't re-enable the extension.

We could add it as an optional permission which every user will have to grant explicitly in the options of Violentmonkey which makes this kinda complicated as you would have to explain it and many users won't see it anyway so I'm not sure this is worth the effort... @gera2ld, thoughts?

**Comment by Invertex** [comment]
> I guess you didn't enable the option in browser settings to prompt saving for each download. Unless this option is enabled we can't force the dialog currently.

I had that option on actually, but it still gives that behaviour where it places a prompt to do "Save-As" up at the top right of the browser *and then* brings up the actual Save-As dialogue afterwards. So the user has to do a Save-As on the content of the page and then click Edge's "Save-As" button top right to finally get the actual Save-As dialogue and choose a location.

<img src="https://i.gyazo.com/be245cfe52cb33eddd888d9141695df7.png"/>

Yet this behaviour of Edge placing it in that top-right menu does not happen with a regular right-click save-as not through scripting.

**Comment by tophf** [comment]
Yes, that's difference explained in my comment.

**Comment by Invertex** [comment]
You claimed I did not have the option enabled, so I was just clarifying, as this whole discussion was *with* the option to always ask enabled. It doesn't force the save-as dialogue regardless.

**Comment by gera2ld** [comment]
`GM_download` works the same as you click on a download button, but not the same as the `Save as...` menu since we don't support the `saveAs` option as in Tampermonkey.
So this is the expected behavior by now.

I prefer not to add `download` permission nor the `saveAs` option to Violentmonkey because there are already plenty of download managers, which prompt before your download starts and handle `save as` operations. I think we should let the right tools do right things.

**Comment by Invertex** [comment]
That's disappointing, as that is not the expected behavior of an addon for userscripts, not to mention it makes the experience of anyone's userscript that uses `GM_download` different between Edge and other browsers. 

I'm not talking about making a download manager here. You talk of letting the right tool do the job, and that's exactly what I'm talking about, letting the browser do the job it's supposed to. Not trying to create a custom save window here. **All I'm asking is for the behavior to be consistent between browsers**, which is that the system default `Save As` dialogue should popup. If this `download` permission is needed to ensure Edge treats the userscript code the same way the other popular browsers do, do you not think that should be enabled?

People installing userscript managers are generally power users, a download permission would not be a hinderance. And just like Tampermonkey, you show the user that the GM_download permission is being used when they install a script.

**Comment by gera2ld** [comment]
`GM_download` is not supposed to show a `Save As` dialog by default, it just tells the browser to start a download and it depends on your browser whether to show a dialog or just save it somewhere. For me this is the consistent behavior because it's telling browser the same thing to do.

I think you are looking for an API to **popup a `Save As` dialog** consistently between browsers, but that's something different from the existed `GM_download`. It's either a new API or `GM_download` with `saveAs` implemented. To me it's a new feature rather than an incorrect behavior to an existed API.

Besides, Edge is trying to handle downloads differently, why do you think we should bypass that behavior and always show a dialog as other browsers do? I suppose people who love Edge may also love the way it handles downloads.

Anyway, I'm not against `saveAs` option and it could be implemented someday. PR is welcome.

**Comment by gera2ld** [comment]
> People installing userscript managers are generally power users, a download permission would not be a hinderance.

That's not true. We have experienced that once. Users seem to think that we are trying to do something bad when a new permission is added.

**Comment by tophf** [comment]
So like I suggested initially **the only** thing we are willing to do is to add an optional permission:

>We could add it as an optional permission which every user will have to grant explicitly in the options of Violentmonkey which makes this kinda complicated as you would have to explain it and many users won't see it anyway so I'm not sure this is worth the effort...

Tampermonkey does the same, BTW.

**Comment by Invertex** [comment]
> Tampermonkey does the same, BTW.

I don't use the `saveAs` parameter in `GM_download` in my script, and in TamperMonkey on Chrome or Firefox it will still pop up the save-as dialogue. Perhaps `saveAs` is set to true as default internally then.


> > People installing userscript managers are generally power users, a download permission would not be a hinderance.
> 
> That's not true. We have experienced that once. Users seem to think that we are trying to do something bad when a new permission is added.

A few users being a little confused isn't really an excuse to reduce capabilities. That's a sure way to end up with a tool the majority won't like if you continually play to the lowest common denominator, imo.

> Anyway, I'm not against `saveAs` option and it could be implemented someday. PR is welcome.

The previous comment made it sound like you were not open to having it added at all. If you are okay with a PR then that is good at least. Then I don't have anything left to say here as the stance has been made clear, cheers.

**Comment by tophf** [comment]
> A few users being a little confused isn't really an excuse to reduce capabilities. 

As an extension developer, I say a lot. And a vocal lot. The majority of users are clueless.

> That's a sure way to end up with a tool the majority won't like if you continually play to the lowest common denominator

Philosophizing and prophesizing aside, what you suggest is solving an edge case at the expense of the majority.

> > Tampermonkey does the same, BTW.
> 
> I don't use the `saveAs` parameter in `GM_download` in my script, and in TamperMonkey on Chrome or Firefox it will still pop up the save-as dialogue. Perhaps `saveAs` is set to true as default internally then.

The comment was describing the technical implementation so "the same" means the implementation part i.e. TM uses an optional downloads permission. Only when a user has enabled this permission in options of the extension, the `saveAs` parameter will actually work. Without this permission it doesn't matter what the parameter is.

As for Chrome or Firefox, unlike Edge, their built-in implementation of script-triggered downloads is traditional, which is why they show the "save as" dialog when the corresponding option is enabled in the browser settings.

To reiterate, implementing `saveAs` option in GM_download per se is a trivial no-brainer but it will work only if we add the `downloads` permission, which we can do only as an optional thing, just like Tampermonkey does it. And like I said, most users don't know they need to grant this permission in the options so you'll have to explain it in your script's description or UI.
