### ISSUE TITLE
[Bug] Google Drive sync doesn't Authorize on Kiwi

### ISSUE THREAD

**Issue by Cyberavater** [violentmonkey/violentmonkey#1396]
Google drive sync is not authorizing for Chromium-based android browser kiwi.

![Screenshot_20211013-212152_Shady_Launcher](https://user-images.githubusercontent.com/32187927/137164827-c13877ba-4551-4830-99ad-1765af01389e.png)

**Comment by tophf** [comment]
I don't know what Tampermonkey does internally and I don't think it would be correct to add yet another workaround for a recent bug in browser, especially one that is probably used by less than 0.1% of our users. Anyway since Violentmonkey worked in earlier versions of Kiwi, we'll wait for a browser fix.

**Comment by candrapersada** [comment]
Ungoogled Chromium: Can't sync via google drive
![image](https://user-images.githubusercontent.com/36833664/142721020-267595ab-7597-46ac-9045-76868c16f664.png)
