### ISSUE TITLE
Request: Add Google Drive to sync options

### ISSUE THREAD

**Issue by ramenchef** [violentmonkey/violentmonkey#141]
I'd like to be able to sync to google drive if possible.

**Comment by ivysrono** [comment]
https://github.com/Tampermonkey/tampermonkey/issues/288
TM4.4+

**Comment by bershan2** [comment]
@ramenchef I just discovered Violentmonkey on Tuesday and would like to see more sync options too. So far, @gera2ld was welcoming [my minor contributions](https://github.com/violentmonkey/violentmonkey/pulls?utf8=%E2%9C%93&q=is%3Apr%20author%3Abershan2%20). So I'll try to add Google Drive when I have time.

@ivysrono It's better to add a small feature (just a bit of API work) to a lightweight extension than to switch to a feature-rich but bloated heavy extension. (By the way, I'm not against any particular extension and I'm glad that there are so many options; however, Tempermonkey is a bit too feature-rich for me.)

**Comment by bershan2** [comment]
@gera2ld I tried OneDrive sync, but could not get it to work. Is there a "switch account" feature? I tried with one account and think I authorized it[1], but it gives "Sync error!".

[1] After I pressed "Revoke" and "Authorize" authorization merely opens a new tab and closes it immediately and tries to sync; I cold not confirm this on the Microsoft account settings because could not find a link to that page).

**Comment by gera2ld** [comment]
@bershan2 You need to log out your <https://live.com> account before another authorization, otherwise you will be authorized immediately with your current account since access is already granted.
"Sync error!" is likely a network problem.

**Comment by bershan2** [comment]
@gera2ld Thanks for quick reply! Unfortunately, I can't do that: I do not have Outlook account, I have only Microsoft account. Details: `https://live.com` redirects me to either:
 - if I do not have cookies, sign in prompt at `https://login.live.com` and an error message at `https://outlook.live.com` after I provide credentials, or
 - if I do have cookies, to `https://outlook.live.com` with an error message right way

Possibly, when I establish sync, the authentication passes with Microsoft account, but actual sync requires Outlook account. I'm really confused now: 
 - why they are not the same thing if [Microsoft worked for so long on it](https://en.wikipedia.org/wiki/Microsoft_account),
- you should not need an Outlook account to use OneDrive, since I have OneDrive. (I don't really use it, but have files in it.)

Are there two different APIs for Outlook and Microsoft account?

**Comment by bershan2** [comment]
Some more confusion:
There is also `microsoftonline.com` with its own authentication `login.microsoftonline.com` serving Office 365... and two different APIs  `graph.microsoft.com` and `contoso-my.sharepoint.com`.

But `api.onedrive.com` is the only one using `login.live.com`.

**Comment by gera2ld** [comment]
@bershan2 You just need to go to <https://login.live.com> and log out. If you want to discuss about it please open a new issue.

**Comment by gera2ld** [comment]
Google drive works really different from Dropbox and OneDrive, may be added in the future.

**Comment by ivysrono** [comment]
googledrive 都实现了，WebDav还会远么？

**Comment by 3v1n0** [comment]
For some reason the Reauthorization here is triggered multiple times a day, not sure why... It happens in all my computers sharing the same account.

**Comment by gera2ld** [comment]
@3v1n0 Because the token expires in very short time, due to limitation of Google Drive.

**Comment by arogl** [comment]
Can this re-authorization  occur in the background rather than opening and closing a tab?

**Comment by gera2ld** [comment]
See #326
