### ISSUE TITLE
GM_getResourceURL is not base64url

### ISSUE THREAD

**Issue by polyproline** [violentmonkey/violentmonkey#1436]
### What is the problem?
GM_getResourceURL is not base64url ,is bloburl. It isn`t excepted!

In violentmonkey console.log(GM_getResourceURL("opencc_wasm")) is
In firefox:
blob:https://visit.domain/7b9cd7fb-af23-4c1b-9a93-47cc8b8ca96d 
In brave:
blob:https://www.baidu.com/631953e4-ced4-4a51-b9a5-014afc9fe2d7
In tampermonkey, it is
data:application;base64,AGFzbQEAAAABeh.........

### How to reproduce it?
1. Install script https://greasyfork.org/en/scripts/413703-opencc-rust
2. Click the violentmonkey menu botton in the opencc-rust "load"
3. The web context should be convert from  Traditional Chinese to Simplified Chinese, but don`t work

### What is the expected result?
Load wasm
The web context should be convert from  Traditional Chinese to Simplified Chinese
The "中文转换" and "事件监听" button should appear in the violentmonkey menu
### What is the actual result?
The code GM_getResourceURL("opencc_wasm") don`t return base64url, it returtn blob url

### Environment
- Browser:firefrox 95.0,brave 1.32.115
- Violentmonkey version: v2.13.0
- OS:ubuntu 20.04LTS

**Comment by tophf** [comment]
The library is making incorrect assumptions. There's no such requirement in the [historical API description](https://sourceforge.net/p/greasemonkey/wiki/GM_getResourceURL/).

**Comment by gera2ld** [comment]
This script is obviously developed for TM as TM defines the result of `GM_getResourceURL` as dataURL.
I think we can keep the current behavior for now.

With a second parameter we may have two types of results: `blobUrl` or `dataUrl`. Even if we support both types, I don't think we will return `dataUrl` by default since `blobUrl` should be more efficient in DOM and that is what `GM_getResourceURL` was designed for.
No matter whether we make a change, script authors will need to know the inconsistence. Besides it's not hard to transform a blobUrl into base64. So why not just keep it as is?

**Comment by tophf** [comment]
@gera2ld, because we store as base64 anyway so for large data it'd be faster to skip transformation if the author wants a specific format. Currently userscripts can't get the data from our blob synchronously, they have to fetch it, which is asynchronous, and fetching blobs may be forbidden by the CSP of the page...

**Comment by gera2ld** [comment]
> fetching blobs may be forbidden by the CSP of the page

Ah that's a valid point.

**Comment by tophf** [comment]
Resolution: the next release will have `GM_getResourceURL(name, false)` to return a data URL.

**Comment by polyproline** [comment]
how can I use GM_getResourceURL to get bytearry? The script need bytearry to load wasm library.

**Comment by polyproline** [comment]
call arrayBuffer() function don`t work with the GM_getResourceURL return value

**Comment by tophf** [comment]
Until the next version is released you need to fetch the blob URL first:

```js
(async () => {
  const url = GM_getResourceURL(name);
  let arr;
  if (url.startsWith('blob:')) {
    const req = await fetch(url);
    const buf = await req.arrayBuffer();
    arr = new Uint8Array(buf);
  } else {
    // decode data: URL directly
  }
  console.log(arr);
})();
```

This example is asynchronous. If necessary, you can use XMLHttpRequest in synchronous mode instead. You can find more examples yourself.

**Comment by tophf** [comment]
The [new beta](https://github.com/violentmonkey/violentmonkey/releases/) implements `GM_getResourceURL(name, false)`.
