### ISSUE TITLE
The page is lagging, when I used injection mode auto or page with F.B. Purity script in Firefox and Chrome

### ISSUE THREAD

**Issue by zurlafaga** [violentmonkey/violentmonkey#1461]
The page is lagging, when I used injection mode auto or page with F.B. Purity script with the latest BETA ViolentMonkey v2.13.0.16.
The issue is affecting both Firefox and Chrome.

### How to reproduce it?
1. Install ViolentMonkey v2.13.0.16 BETA.
2. Install the F.B. Purity script from https://www.fbpurity.com/fbpurity.THRTYX.user.js
2. ViolentMonkey is using injection mode auto or page in Firefox or Chrome.
3. Logging in Facebook account.
### What is the expected result?
Scroll the page without lag.
### What is the actual result?
The page is lagging, especially when we are trying to reach the bottom of the page.
### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?
The lag is NOT present in ViolentMonkey 2.13.0 and in ViolentMonkey 2.13.0.16 BETA injection mode: content.
### Environment
- Browser: Firefox and Chrome
- Browser version: Multiple versions
- ViolentMonkey version: ViolentMonkey 2.13.0.16 BETA
- OS: Windows 10

**Comment by tophf** [comment]
I don't have an account there and we generally don't debug userscripts.

**Comment by zurlafaga** [comment]
ViolentMonkey v2.13.0 is working without lag in both Firefox and Chrome.

ViolentMonkey v2.13.0.16 BETA is lagging if the injection mode is auto or page. If injection mode is content in this version, there is no lag. That's in both Firefox and Chrome.

**Comment by tophf** [comment]
What is the latest beta that works for you? Can you give me a URL to reproduce the problem without signing in?

**Comment by tophf** [comment]
Also try setting run mode to document-body:

![image](https://user-images.githubusercontent.com/1310400/154734370-8e2f846b-5419-49e7-8263-a74a8de66ecd.png)

P.S. Note that if the problem requires an account we won't be able to solve it because I won't register there.

**Comment by tophf** [comment]
Thanks. Hopefully someone else with an account on facebook would be able to investigate it further.

**Comment by zurlafaga** [comment]
@tophf, I don't have access to older builds. The files are marked like "Expired".

**Comment by tophf** [comment]
I was able to register an account on facebok, had to input my phone number, which I hate, but hopefully it won't leak anywhere.

I don't see lags, but I see 100% CPU utilization and a lot of messages in devtools console printed by this script about being unable to hide group convos. I looked at the code of the script and couldn't find the reason because there's a lot of code. What I saw is that it's using timers and polling instead of using the modern proper API like MutationObserver and IntersectionObserver. I'm afraid only the author of the script can find the reason.

**Comment by tophf** [comment]
Setting script's `run-at` to `document-end` removes the console messages, so if it fixes the lag for you as well, then the most likely reason is a bug/mistake in the script, which surfaces only in new Violentmonkey because we improved the speed of our injection at document start in auto/page mode. It seems the script sets a timer when it doesn't find `document.head`, forgets to cancel it, then more timers spawn progressively causing the lag. You can suggest the author to use `document.documentElement` to add its styles and other stuff.

**Comment by zurlafaga** [comment]
@tophf, you can always request your account and the information in Facebook to be deleted.

Your words make sense but I made the report, because I didn't know the root problem and the lag is only present in ViolentMonkey.

If I run the script with document-end or document-idle, the lag is disappearing but I see additional problems, which are maybe related to the script.

I appreciated your effort.
