### ISSUE TITLE
Link to script home page

### ISSUE THREAD

**Issue by ExDeF** [violentmonkey/violentmonkey#156]
Hi! Please add a links to the script's home page as in Tampermonkey.

**Comment by bershan2** [comment]
@ExDeF There are links to scripts' home pages already: they are in the scripts titles.

**Comment by ExDeF** [comment]
It is not comfortable. Better button with a link to the site.

**Comment by bershan2** [comment]
So something like this?
![icon](https://user-images.githubusercontent.com/22861096/28147554-0c9d25a8-6747-11e7-9d13-14df916a7bb8.png)

**Comment by ExDeF** [comment]
Yes. Thanks!

**Comment by bershan2** [comment]
@ExDeF Well, I did not do anything yet (that was just quick-and-dirty edit of the page itself) and I am not the creator of this extension, so this idea is still up in the air.

@gera2ld How do you like this?

**Comment by gera2ld** [comment]
I think it is not comfortable to have too many buttons, which are small and ambiguous.
If we have to do this, how about putting all the icons together at the bottom?

**Comment by bershan2** [comment]
@gera2ld Please disregard the commit that I just pushed: I did not see your message.
> how about putting all the icons together at the bottom?

That would even increase the confusion, I think: the buttons below are "action" buttons, while the `homeUrl` and `script.meta.supportURL` are actual "informative page" URLs -- they do not invoke immediate action, just take you somewhere outside. (I call "Edit" button "action button" since it is intended for an action, even though you could open it just to look at the code).

**Comment by AlexBeLi** [comment]
@gera2ld May you change position of trash button to the right edge? It's no good that instead enabling/disabling script people can remove script by mistake.

**Comment by gera2ld** [comment]
@AlexBeLi That makes sense.

**Comment by bershan2** [comment]
@gera2ld @AlexBeLi How about asking for a confirmation instead? On the right you still can accidentally click the button while trying to drag the script or see the author's email.

Removing a script can be irreversible (if no backups are enabled), therefore I believe actual confirmation would be appropriate.

**Comment by gera2ld** [comment]
@bershan2 I think an `undo` operation feels better than a confirmation for each click. This will be added in the future.

About this issue, @ExDeF @bershan2 why do you guys prefer the icon link? What about putting them at the bottom and add a separator between the information buttons and action buttons?

![image](https://user-images.githubusercontent.com/3139113/28930656-39c974ee-78a6-11e7-92df-daafb5f3b9b0.png)

**Comment by bershan2** [comment]
@gera2ld I never complained about design since the replacement of text buttons with icons, so you shouldn't ask me. However, this does look much cleaner (without colors), I think. The only suggestion I have is: how about giving more space to the script icon (Octocat in this case)? Specifically, letting it occupy the entire vertical distance and moving buttons to the right, under the script name and description. I mean something like this (but properly centered and aligned):
![28930656-39c974ee-78a6-11e7-92df-daafb5f3b9b0](https://user-images.githubusercontent.com/22861096/28936150-6ba35d18-784c-11e7-9dc4-6f0c76aaa2c0.png)
