### ISSUE TITLE
[BUG] GM_download does NOT save the files in Release 2.13.1

### ISSUE THREAD

**Issue by Nampo** [violentmonkey/violentmonkey#1566]
- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
GM_download does NOT save the files in Release 2.13.1
Verified with the GM_download(options) syntax, not tested with GM_download(url, name)
Verified using Firefox 104.0.2 (64-bit).

**To Reproduce**
1. just make a script and call GM_download() with valid options
2. run it
3. observe that every callback is called correctly
4. observe that no file is saved in the Firefox download directory

**Expected behavior**
Downloaded files should be saved on disk.

**Actual behavior**
No files are saved anymore

**What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?**
WARNING! Do an export in settings before testing!

no relevant or unexpected console messages

**Environment:**
- OS: Windows 10 Pro
- Browser: Firefox 
- Browser Version: 104.0.2 (64-bit)
- Violentmonkey Version: 2.13.1

**Additional context**
Previous versions of Violentmonkey still work as expected.
Also, any news about "saveas" implementation ? we can't organize downloads from scripts, otherwise!
Also, docs should be enhanced and fixed, e.g. GM_download "onload" callback is for when the download ENDS, not for when it starts.

**Comment by tophf** [comment]
Fixed in 84373a9f. I'd say this warrants a new release together with 710bc884, @gera2ld.

> "saveas" implementation

There's a separate issue for that, no news.

>  "onload" callback is for when the download ENDS, not for when it starts.

Well, the event is fired when the browser's downloading API is triggered to save the data to a possibly slow disk, which is what the documentation tried to convey, but I agree it's confusing because downloading normally always means network activity. I'll try to rephrase it.
