### ISSUE TITLE
[BUG] Google Drive sync not working in firefox for Version 2.13.1

### ISSUE THREAD

**Issue by zihadio** [violentmonkey/violentmonkey#1571]
The latest 2.13.1 version don't sync with google drive. But previous version 2.13.0 works. 
https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/versions/

So, I went to install previous version. I am using Flatpak version of Firefox in linux.

```
Unable to connect

Firefox can’t establish a connection to the server at 127.0.0.1:45678.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.
```

**Comment by tophf** [comment]
@gera2ld, was this 127.0.0.1 here a typo? https://github.com/violentmonkey/violentmonkey/blob/7d10610f13a15c0a173c45659fdb1bbcf8eb05b6/src/background/sync/googledrive.js#L17

**Comment by gera2ld** [comment]
No, it's intended. Because I changed the OAuth process to the safer native app approach but Google only allows loopback IP address as its callback URL. The URL will be intercepted by `onBeforeRequest` so it doesn't matter what the URL is.
Just did some quick test, and it seems that Firefox does not support match patterns with port number in it. Let me fix it.

**Comment by notetiene** [comment]
It looks this kind of URL doesn't work in Firefox for Android (Nightly).
