### ISSUE TITLE
Improve Recycle bin navigation and discoverability

### ISSUE THREAD

**Issue by nropgrammer** [violentmonkey/violentmonkey#1583]
- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
Viewing the garbage prevents the user from viewing the installed scripts. The `scripts` url hash must be removed to get back to installed scripts

**To Reproduce**
1. Go to garbage
2. Click on installed scripts
3. Observe how it does not go back

**Expected behavior**
Go back to installed scripts

**Actual behavior**
Does not go back to installed scripts

**What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?**
The same

**Environment:**
- OS: macOS
- Browser: chrome
- Browser Version: 105.0.5195.125
- Violentmonkey Version: v2.13.1

**Comment by nropgrammer** [comment]
My apologies for the missing title. I was unaware that it is not possible to add labels yourself and pressed enter after trying to add the `ui` label

**Comment by tophf** [comment]
Currently this is the intended behavior: you need to click the recycle bin icon again to go back. I agree this may seem counter-intuitive because it's an unexpectedly different method to navigate in the UI. I already had an idea to make a `Removed scripts` tab under the `Installed scripts` tab. @gera2ld, thoughts?

**Comment by nropgrammer** [comment]
Ahh I see that now.
I think a `Removed scripts` tab would make more UI sense, or perhaps changing the garbage can to a back arrow like:
![889590](https://user-images.githubusercontent.com/47487649/192074060-0ccac994-d3e0-4b8f-9513-a328c60e9c47.png)
I just don't think it's clear that the same icon, which doesn't change, can both bring you to the page and back. However I could just be extra clueless and the only person who thought this was a  bug.

**Comment by gera2ld** [comment]
I agree to have a back button on the top (`←`), I feel a new tab for recycle bin is too strong.

**Comment by tophf** [comment]
I disagree. The UI navigation will still be broken just like it is now because the labels in the navigation panel won't be clickable. There is already a back button in the browser, as well as forward so we should just use them. Also, making the recycle bin prominent will be good to show people they have something there. For example currently they can't write a new script if it's in the recycle bin, which means they forgot about its existence because the recycle bin is almost hidden from sight.

**Comment by gera2ld** [comment]
I see, a new tab is fine. I misunderstood the idea of tab.

> currently they can't write a new script if it matches one in the recycle bin

Actually I think this is a bug that we should handle.

**Comment by tophf** [comment]
If we decide to implement it as a "tab".
* We can hide Recycle bin "tab" when it's empty because there's no useful functionality inside in this case.
* When it has scripts the number will be shown as `(2)` for example.
* Maybe add an option to customize the duration (suggested in #1535) inside the Options minipanel.

If it is a "label" we might show a filtering toolbar where each item has a state selector (+, –,?):
`[+] Removed` `[–] Updatable` `[?] Enabled` `[?] Custom settings` `[?] Storage`
