### ISSUE TITLE
why violentmonkey in chrome is newer than firefox？

### ISSUE THREAD

**Issue by whonchen** [violentmonkey/violentmonkey#165]
now， chrome is v2.72，firefox is v2.63， why？

**Comment by gera2ld** [comment]
Because the review takes quite long time, and even longer if code is compressed. We are going to improve this by providing an uncompressed version for Firefox.

**Comment by gera2ld** [comment]
See also #162

**Comment by mrdokenny** [comment]
@gera2ld I recommend going to the Reviewers IRC to get your extension out of the admin queue if you recently uploaded the uncompressed version. From what I know, your extension will still go into the admin queue for future versions, unless someone takes it out.

https://wiki.mozilla.org/Add-ons/Reviewers

irc://irc.mozilla.org/addon-reviewers

**Comment by spodermenpls** [comment]
@gera2ld Is there progress on the review issue at AMO, were you able to get it out of the admin-only channel? Violentmonkey has not seen an update in 4 months for Firefox users, which is quite a shame looking at all the effort and improvement that went into it since, being not accessible for me and others.
