### ISSUE TITLE
Firefox CSP issue

### ISSUE THREAD

**Issue by gera2ld** [violentmonkey/violentmonkey#173]
Firefox does not support script injection from extension when page has CSP restrictions. As a result, no script can be injected to such pages in Firefox. But it works well with Chrome.

Related issues:
#107, #172 

Some examples suffered from this issue:
- scripts cannot work correctly on Github
- styles installed via userscript cannot be applied on Github

**Comment by d4k0** [comment]
If this is an issue with Firefox, then why do the scripts work in Tampermonkey? Or does Tampermonkey use some kind of workaround?

**Comment by gera2ld** [comment]
Because it has modified the CSP header. And this seems to be the only solution on Firefox if Firefox won't grant permission for extensions to inject scripts.

**Comment by nkestrel** [comment]
Upstream [Bug 1267027](https://bugzilla.mozilla.org/show_bug.cgi?id=1267027).

**Comment by angelsl** [comment]
FWIW I'm currently working around this using [an addon to modify the CSP per-page](https://github.com/angelsl/cspoverride/releases/tag/v1.2.1) ([slightly modified](https://github.com/Rufflewind/chrome_cspmod/compare/master...angelsl:master) from the [original Chrome extension](https://github.com/Rufflewind/chrome_cspmod)).

**Comment by Geobert** [comment]
I can ditch Tampermonkey now! Cheers @angelsl !

**Comment by Geobert** [comment]
Good news: https://bugzilla.mozilla.org/show_bug.cgi?id=1267027#c21

**Comment by Betsy25** [comment]
FYI, Normally this issue should be fixed in the latest Firefox Nightly.
https://bugzilla.mozilla.org/show_bug.cgi?id=1406278

**Comment by alphabug** [comment]
I didn't want to install another addon just to tinker with CSP headers so for the time being, short of disabling CSP altogether, I loosened the policy with the about:config switch security.csp.enableStrictDynamic = false to continue running (dynamically injected) userscripts while continuing to block normal page scripts.

**Comment by evilpie** [comment]
With both [bug 1407056](https://bugzilla.mozilla.org/show_bug.cgi?id=1407056) and [bug 1406278](https://bugzilla.mozilla.org/show_bug.cgi?id=1406278) fixed this should now work correctly. For example testing the script from #172 on github everything seems correct with Firefox 58 (2017-10-20). @gera2ld can you confirm?

**Comment by gwarser** [comment]
Not work. Even in Tampermonkey CSP hack is required.

**Comment by angelsl** [comment]
@gwarser

The changes in question will only land in FF 58.

You may wish to try the next Nightly containing those changes.

**Comment by gwarser** [comment]
I'm on Build ID 	20171021100029

**Comment by kasper93** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1267027

**Comment by Toora** [comment]
Is this script not working related to the CSP issues? [Extract images for Twitter](https://greasyfork.org/en/scripts/15271-extract-images-for-twitter)

Works with Tampermonkey and Greasemonkey 4, but not Violentmonkey. Also not on latest Nightly.

**Comment by evilpie** [comment]
Actually I was wrong, it still doesn't seem to work. Both the github script and the twitter script in the image above still run into CSP issues.
Talking to the developer following things are still missing:

> \<John-Galt\> There is more to do, yes: inline styles, content injected from inline stylesheets, support for innerHTML, eval, inline scripts (which I probably won't actually implement)... a few other things. But most basic injections should work now.

Maybe the way Violentmonkey injects scripts could be changed.

**Comment by evilpie** [comment]
Checkout https://github.com/evilpie/violentmonkey/commit/18f5c60f6316dfc249919389d5d439cea4a88f6f. This seems to make the script from #172 work for me. [Extract images for Twitter](https://greasyfork.org/en/scripts/15271-extract-images-for-twitter) also works, but it seems a bit broken, but this is probably unrelated to the CSP issue.

The fix is to use `.src` for injecting the scripts instead of using `.textContent` (i.e inline scripts), which might not even be fixed.

**Comment by Geobert** [comment]
It's broken again since a day or two :( 

Had to use @angelsl [workaround again](https://github.com/violentmonkey/violentmonkey/issues/173#issuecomment-327869792)

**Comment by jsamr** [comment]
@gera2ld  
A folk on [this bugzilla ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1267027) suggested to use contentScripts API to bypass CSP restrictions.

> Can’t you use the the `contentScripts` API¹?
> ¹ https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/contentScripts

**Comment by danShumway** [comment]
What would be the biggest hurdle in moving over to contentScripts?

As far as I can tell:
- Chrome doesn't currently support them.

Otherwise, ``run-at`` seems to support the same options. If there was an alternate method for Chrome, would I be correct in assuming this is something that could be swapped in for the [injection bridge](https://github.com/violentmonkey/violentmonkey/blob/ac125f69355d5c4fec4016d33ef7c5458dcc229d/src/injected/web/index.js)? Since ``contentScripts`` will only register for the duration of the object lifecycle, seems like something that could be registered on each page load. Not sure if that would have performance implications.

**Comment by gera2ld** [comment]
By using `contentScripts`, it's impossible for Chrome to access `unsafeWindow`.
Even in Firefox many scripts will be broken because of access to incorrect global objects. For example, there will be two different `Array` prototypes, one from the content script, and the other from the web page. When calling an array created in the web page from the content script, a *DOM Exception* will be raised. As a result, `unsafeWindow` becomes useless though you have `wrappedJSObject`.

**Comment by danShumway** [comment]
Yeah, you're right; forgot that ``@grants`` means that scripts can actually request access to that stuff.

I'd still be happy with even a limited way to get scripts interacting with CSP-blocked domains, since right now the alternative is nothing works at all; but since Firefox is theoretically still planning to just make CSP not apply to injected scripts, it's probably more efficient for me to just bug them about it.

**Comment by oifj34f34f** [comment]
I can't run userscripts on GitHub.com. Has anyone found a solution? @angelsl :)

**Comment by tophf** [comment]
Set `Injection mode` to `Auto` in the options.

**Comment by oifj34f34f** [comment]
Doesn't work :(
and it was already enabled by default.

**Comment by tophf** [comment]
Use GM_addStyle or GM_addElement.

**Comment by vintprox** [comment]
Hm, I tried this:
```
// ==UserScript==
// @name        Mastodon Wider Columns
// @namespace   https://greasyfork.org/en/users/830433-vintprox
// @match       https://techhub.social/deck/*
// @grant       GM_addStyle
// @version     1.0
// @author      vintprox
// @description Make an "advanced web interface" a little bit better on Mastodon by widening columns
// ==/UserScript==

GM_addStyle(`
  .drawer {
    width: 400px;
  }
  .column {
    width: 400px;
  }
  .column:last-child {
    flex-grow: 1;
  }
`);
```

Doesn't cut it, unfortunately.

**Comment by tophf** [comment]
37ec0113 fixes it. Test build in [CI](https://github.com/violentmonkey/violentmonkey/actions/workflows/ci.yml).
