### ISSUE TITLE
[BUG] TypeError: DOMParser.parseFromString: 'application/json' (value of argument 2) is not a valid value for enumeration SupportedType.

### ISSUE THREAD

**Issue by qinxs** [violentmonkey/violentmonkey#1734]
- [x] The bug is also present in the latest [beta](https://github.com/violentmonkey/violentmonkey/releases).
   Warning! Do an export in Violentmonkey settings before testing.

- [x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**

油猴脚本 [Super_preloaderPlus_one_改](https://github.com/machsix/Super-preloader) 不能更新规则。

控制台错误如下：
> TypeError: DOMParser.parseFromString: 'application/json' (value of argument 2) is not a valid value for enumeration SupportedType.

**Environment:**
- OS: Win7 x64
- Browser: Firefox 
- Browser Version: 102.7.0esr (64 位)
- Violentmonkey Version: 2.13.X（2.13.5到2.13.9都不能更新）

**Additional context**
![error](https://user-images.githubusercontent.com/13647698/214849412-69ca755b-1d71-4a17-b9fc-d41f4002185e.png)

经测试，
Violentmonkey 2.12.13没问题，2.13.X都不能成功（仅2.13.5有详细的错误提示，如上图）

**Comment by gera2ld** [comment]
Can you provide the steps to reproduce the issue? like open which page, click which button

**Comment by tophf** [comment]
Apparently this is caused by `Object.assign(nodeResponse, xmlResponse);` line in this script. It tries to read all props including `responseXML` and our code incorrectly tries to parse the response as xml. Looks like I misunderstood the documentation for `responseXML` - we should return `null` for anything that cannot be parsed without surfacing the error.
