### ISSUE TITLE
[BUG] Web Locks API doesn't work with Noscript or uBlock scripts blocked

### ISSUE THREAD

**Issue by Zipdox2** [violentmonkey/violentmonkey#1755]
### Sequence of actions: 
1. Install noscript or block scripts by default in uBlock Origin
2. Install this script:
```javascript
// ==UserScript==
// @name        Web Locks test
// @match       https://example.com/*
// @grant       none
// @version     1.0
// @author      -
// ==/UserScript==

function delay(ms){
    return new Promise(resolve=>{
        setTimeout(resolve, ms);
    });
}

navigator.locks.request('test', {mode: 'exclusive', ifAvailable: false, steal: false}, async ()=>{
    console.log('Hello, world!');
    await delay(20000);
});
```
3. Open two blank tabs and open the consoles
4. Navigate both tabs to https://example.com

### Problem: 
Both scripts print hello world immediately. There is also an error (will show below).

### Expected result:  
One script waits 20 seconds for the lock on the other script to release before printing hello world.

#### Devtools console contents:
```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). injected.js:1:8970
Hello, world! Web Locks test.user.js:16:13
Uncaught (in promise) Error: Permission denied to access property "then"
```

#### Environment:
- OS: Debian sid
- Browser: Firefox 109.0 (64-bit)
- Violentmonkey Version: v2.13.10

**Comment by tophf** [comment]
I can't reproduce the problem. Anyway, this is working as intended because the script runs in the default (main) JS world of the page, so all the restrictions installed by other extensions in the page apply to it. You can add `@inject-into content` to run the script in an isolated JS world.

**Comment by tophf** [comment]
Sorry, forgot how to configure uBlock. Now I see the error and my suggestion above won't help. I'll investigate further.

**Comment by Zipdox2** [comment]
> @inject-into content

I tried this, it still doesn't work.

**Comment by tophf** [comment]
Yes, like I said my suggestion won't work. There's no solution, AFAICT. It's a bug in Firefox that can be reproduced by putting this code in a content script of any extension. It applies to your script because when the CSP blocks inline scripts we inject the code in the isolated JS world of the content scripts.

**Comment by Zipdox2** [comment]
Would it be possible to add an API to Violentmonkey for this kind of functionality?

**Comment by tophf** [comment]
Since we can't use it in our content script I don't see how we can support it. Maybe you can use [GM_addValueChangeListener](https://violentmonkey.github.io/api/gm/#gm_addvaluechangelistener).

**Comment by Zipdox2** [comment]
> Maybe you can use [GM_addValueChangeListener](https://violentmonkey.github.io/api/gm/#gm_addvaluechangelistener).

Yes I'm trying to use this, but this pretty difficult because when the page closes the values don't get deleted, meaning the lock doesn't get unlocked.

**Comment by tophf** [comment]
BroadcastChannel + send a ping message periodically to detect alive tabs might be slightly better than GM_addValueChangeListener because it doesn't need to update the storage on disk.

> Would it be possible to add an API to Violentmonkey for this kind of functionality?

Actually, it's possible if we won't be using `navigator.locks`. I can see the appeal of such an API because there's no good solution currently neither in Violentmonkey nor in Tampermonkey.

Maybe you could suggest the shape of such an API in a new issue here or in Tampermonkey? It doesn't have to replicate all the bells and whistles of navigator.locks (if it has any), just show a few examples that demonstrate how the API could be used.

**Comment by Zipdox2** [comment]
It doesn't really have any bells. It's basically just an async mutex.

**Comment by tophf** [comment]
So `GM_mutex('name', callback)` and `GM.mutex('name'): Promise` ?

**Comment by Zipdox2** [comment]
It needs to take a callback **and** return a promise. The callback is an async function that gets run when the mutex gets locked, and the returned promise resolves after the callback has completed.

**Comment by tophf** [comment]
So there are some bells: https://developer.mozilla.org/en-US/docs/Web/API/LockManager/request

**Comment by Zipdox2** [comment]
I know, they could be implemented, but they aren't really that important. The default behavior is what most users are looking for.

**Comment by tophf** [comment]
We usually don't add new API first unless it exists in Tampermonkey or elsewhere and is already used by userscripts. If we are to add this API first we need to think it through so that it's extensible in the future. Maybe you can suggest something here or in Tampermonkey repository, otherwise I don't think I'll be doing anything myself as I don't write such complex scripts.

**Comment by Zipdox2** [comment]
I'll have to think about it.
