### ISSUE TITLE
Impossible to update a script installed from a `file://` URL

### ISSUE THREAD

**Issue by AlttiRi** [violentmonkey/violentmonkey#1758]
I tried to install a script as it's suggested here: [how-to-edit-scripts-with-your-favorite-editor/#install-a-local-script](https://violentmonkey.github.io/posts/how-to-edit-scripts-with-your-favorite-editor/#install-a-local-script)

It works.

However, it does not updates the installed script neither after updating the local file (with a site reload), or after reloading the extension.

The reload button in the scripts list is disabled too.

```js
// ==UserScript==
// @name        file://script.user.js
// @version     0.0.1
// @namespace   gh.alttiri
// @match       *://example.com/*
// ==/UserScript==

document.body.innerText = "Qwerty-0.0.1";
```

---
- Chromium
- Violentmonkey 2.13.3.7, 2.13.11 (latest)

**Comment by AlttiRi** [comment]
Oh, wait. I did not note the checkbox:

![image](https://user-images.githubusercontent.com/16310547/219903987-157bfa56-45c0-497f-bf46-95a0db49ffca.png)

...since it was gray colored.

**Comment by tophf** [comment]
Currently we intentionally allow auto-updates only for remote URLs not file://.
I guess it might be an oversight because there should be no reason to disallow it, @gera2ld?

**Comment by tophf** [comment]
The opacity bug is fixed in 3357220e.
Regardless of our decision on auto-update you can use the "track" option with local files.

**Comment by AlttiRi** [comment]
With this checkbox the updating is working, _until the installation page is not closed._

From docs:
> After installation, the confirmation page will keep watching the file before the page is closed.

Technically, is it not possible to watch for the changed after closing the page, or the extension reloading?

**Comment by tophf** [comment]
Yes.

**Comment by gera2ld** [comment]
The reason why auto-updates for `file://` are disabled is because they are unportable and unpredictable (the same path may lead to different contents on different devices).

This is not right for a web extension which is supposed to work across devices or even without a specific device. A similar situation is that, you can't expect a website to require a file from someone's computer, though it might be convenient when you develop this website locally.

That being said, if we still want to allow update for `file://`, despite that it may not work on a different device, I guess we need to make sure the download URL is set to `file://` locally but not synced to remote. We have to handle the URLs differently in many places. That's a lot of special logic to handle from my point of view and I don't think it's worth the effort.
