### ISSUE TITLE
[Feature] @nocors metadata block

### ISSUE THREAD

**Issue by sjehuda** [violentmonkey/violentmonkey#1781]
**Motivation**
Uniformity of userscript managers.

**Proposed Solution**
`@nocors` metadata block.

I think it would be useful to add `@nocors` metadata block (similarly to `@noframes`) which would be productive in the sense of coding and consequently make userscript managers to behave in a uniform fashion.

**Use Cases**
[no-www](https://openuserjs.org/scripts/sjehuda/no-www) is using `GM.xmlHttpRequest` which doesn't seem to be supported with all userscript managers.

Example script
```js
// ==UserScript== 
// @name        no-www
// @namespace   org.openuserjs.sjehuda.no-www
// @description www. is deprecated. Redirect to URL without www.
// @author      Schimon Jehudah, Adv.
// @homepageURL https://no-www.org/
// @supportURL  https://openuserjs.org/scripts/sjehuda/no-www/issues
// @updateURL   https://openuserjs.org/meta/sjehuda/no-www.meta.js
// @copyright   2023, Schimon Jehudah (http://schimon.i2p)
// @license     MIT; https://opensource.org/licenses/MIT
// @run-at      document-start
// @include     *
// @grant       GM.xmlHttpRequest
// @version     23.03
// ==/UserScript==

if (!location.host.startsWith('www.')) return; // exit (else, continue)

var newURL = location.href.replace('://www.','://');

GM.xmlHttpRequest({
  method: 'GET',
  url: newURL,
  onprogress: console.log('Checking for no-www...'),
  onload: function(response) {
    if (response.finalUrl == newURL) {
      location.href = newURL;
    } else {
      console.log('Please contact webmaster to remove www. https://no-www.org/');
    }
  },
  onerror: function(response) {
    console.log('Error requesting for no-www')
  }
})
```

If `@nocors` was introduced, this script could have been shorter.
```js
fetch(newURL)
  .then((response) => {
     if (request.reseponseURL == newURL) {
       window.open(newURL,'_self');
     }
  })
```

**Comment by sjehuda** [comment]
Discussion at https://openuserjs.org/discuss/nocors_metadata_block

**Comment by tophf** [comment]
I'm against this because 1) there's already a simple solution and 2) extensions can't actually disable CORS which means we would have to patch `fetch` and `XMLHttpRequest` but we can't patch other methods of delivering remote content for DOM elements or script executed via a dynamic `import()` which would mean the feature is a half-broken toy.

You can `@require` a library that implements this functionality. And if none of the existing satisfies you , write a new one.

**Comment by tophf** [comment]
Another big problem is the complexity of polyfilling streams/blobs in the response as the actual request will be performed in the background script the extension would have to transfer the data explicitly and recreate the data. Hiding this machinery from the userscript author creates a false impression that it's not costly while actually it is very very costly both in terms of performance and the maintenance burden of the authors of a userscript extension. There will be also problems with different behavior of headers due to the origin of the request being inside the extension, so the extension would have to patch the outgoing/incoming headers differently in different browsers, because they do it slightly differently. It might be even impossible in ManifestV3 because it removes webRequestBlocking and allows a primitive declarativeNetRequest for normal extensions not installed via policies.
