### ISSUE TITLE
[Feature] add release notes to https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/versions/

### ISSUE THREAD

**Issue by rezad1393** [violentmonkey/violentmonkey#1782]
**Motivation**
when user updates the addon from firefox , he should see the changelog and not have to search for them in github page.

**Comment by tophf** [comment]
Technically, we don't have the human-readable changelog when we publish a release. We only have a machine-generated list of commits that is incomplete and hard to understand, so we can't just post it as-is.

After we publish a github release we usually write the changelog manually. Strictly speaking, there's no need to do it. There's a commit log that contains all the technical info for curious people.

I also don't like the idea of manually copypasting the changelog to the addons site because it's extra work to make sure it looks right (AMO doesn't support github markdown) and I don't even use Firefox.

I think we can just add `Changelog: https://github.com/violentmonkey/violentmonkey/releases` to the description.
@gera2ld?

**Comment by gera2ld** [comment]
Yep I agree, we are trying to make everything automatic so I guess no one wants to copy and paste the changelog.

**Comment by rezad1393** [comment]
I understand.
I just wanted to see release notes (not necessary changelog) when I update addon from firefox and not have to got to github to see them.

**Comment by tophf** [comment]
We don't have release notes.

**Comment by rezad1393** [comment]
> We don't have release notes.

I meant this:
[v2.14.0](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.14.0) [Latest](https://github.com/violentmonkey/violentmonkey/releases/latest)

Notable changes:

    Restored dashboard favicon in Firefox.

    Fixed opening links from popup in Firefox.

    This is the last version for Firefox 52. The minimum in the next Violentmonkey will be Firefox 57 (Quantum) because it's the first version that properly supports various browser API used in Violentmonkey, i.e. in Firefox 52-56 the extension was partly broken.

The version string is shorter now:

    Stable releases will only increment the second number and always end with a 0.
    Beta will have a nonzero number at the end: 2.14.1, 2.14.2 etc.

Commit log: https://github.com/violentmonkey/violentmonkey/compare/v2.13.11...v2.14.0

**Comment by tophf** [comment]
This is a changelog.
