### ISSUE TITLE
[BUG] Does not run the latest script

### ISSUE THREAD

**Issue by TimidScript** [violentmonkey/violentmonkey#1793]
### Sequence of actions: 
1. Alter a script while file tracking is turned on. 
2. Press F5 to refresh page and it runs old version of the script.

### Problem: 
Runs old version of the script no matter how many times I update the script. When I open the script in VM, it shows latest version. If I reboot FF, latest version of the script is run.

I am not to sure how to reproduce, this. I uninstalled VM and reinstalled scripts from archive and it works for a while as expected but then it stops working.

#### Devtools console contents:
No errors

#### Environment:
- OS: Windows 10
- Browser: FIreFox Portable 111.0.1 (64-bit)
- Violentmonkey Version: 2.14.0

**Comment by tophf** [comment]
Try disabling `Alternative page mode in Firefox` in advanced settings.

**Comment by TimidScript** [comment]
Not sure where this (advance) setting is at. If you mean about:config, I could not find it. And the main settings search returns nothing for alternative page.

**Comment by TimidScript** [comment]
It does not make a difference. The bug is still there.

**Comment by tophf** [comment]
Well, unfortunately there's nothing I can do without an exact sequence to reproduce the problem. It may be also a bug in Firefox, so maybe you can verify it in [mozregression](https://mozilla.github.io/mozregression/)?

**Comment by TimidScript** [comment]
Fair enough. Thx.

(Just let you know that if I alternate between injection options (page, content), then update, it works. But I have to alternate between each update.)

**Comment by tophf** [comment]
From what I see in the source code, if toggling injection influences this problem then disabling "Alternative page mode" should have helped too, but you said it didn't help.

Maybe you can find the latest [Violentmonkey beta](https://github.com/violentmonkey/violentmonkey/releases) that doesn't have this bug?

**Comment by TimidScript** [comment]
Nope, it does not make a difference. 

I just tried it in normal FF and it works fine. It something to do with FF portable, which is very odd. Because a few days ago it was working fine.

**Comment by T1mL3arn** [comment]
Have the same issue. "Alternative mode" didn't help. Also found that after ~5min the actual version of a script finally runs.

**Comment by tophf** [comment]
5 minutes is the duration of our injection cache, so apparently there's a mistake somewhere in clearing the cache for an edited script...

**Comment by T1mL3arn** [comment]
Can it be script-related thing? I am testing small `console.log()` and do not see the problem (it is the only script on a page). But when I enable some other large script and edit any of them, I get no changes on the page (despite I clearly see the changes in the VM editor).

**Comment by T1mL3arn** [comment]
>alternate between injection options But I have to alternate between each update

disable-enable "alternative page mode" worked for me the same way:

- update the script
- disable-enable "alternative page mode"
- reload tab when my script is running
- finally see the changes

**Comment by tophf** [comment]
Is there an error in the [background console](https://extensionworkshop.com/documentation/develop/debugging/)?

**Comment by T1mL3arn** [comment]
No errors. Tested VM v2.14.0 and FF v110.0.1.

**Comment by gera2ld** [comment]
I've encountered this issue several times recently in the latest Chrome, will look into it some day.

**Comment by tophf** [comment]
Hmm, maybe it's because we are [deleting the extra key](https://github.com/violentmonkey/violentmonkey/blob/2bd8a5fa4b4dfee1abf914593e1623d4b9dfa6b3/src/background/utils/preinject.js#LL42C40-L42C40) that wasn't enumerated yet in [cache.destroy](https://github.com/violentmonkey/violentmonkey/blob/2bd8a5fa4b4dfee1abf914593e1623d4b9dfa6b3/src/common/cache.js#L78)? Generally it's considered safe to delete only the current key or previously enumerated keys in the loop.

**Comment by virtuallyunknown** [comment]
I'm having the same issue on Firefox 116.0.3 on Linux and Violentmonkey 2.15.0.

Tracking local script seems to just randomly stop working, and I have no idea why. Since I am serving my script file from a local server, I can see that new requests are being made by Violentmonkey every second, however the script is not being updated and when your run a page that `@match`-es the script, it's still runs the previous version of the script. This makes developing a pretty painful experience.

Toggling the `Alternative Page Mode in Firefox` on or off doesn't seem to make any difference. I should also mention that this has been an issue for a very long time, because I remember I was having this problem while developing [this user script](https://github.com/barca-reddit/strawpoll-userscript-react) about an year ago.

When it gets in this "stuck" state where it won't update the script, there are two things that seem to work but not all the time. You can go to the page where you installed the script, refresh it and then click on `Confirm re-installation` again, then refresh your `@match` page.

![image](https://github.com/violentmonkey/violentmonkey/assets/24871108/423116cd-57f5-4c39-ba92-e6c5fcf65ebb)

In development I also have [chokirar](https://github.com/paulmillr/chokidar) that watches my `src` directory for file content changes and then rebuild/compiles the user script in my `dist` directory, which is the file I serve locally to violentmonkey, for example `localhost:3000/dist/script.user.js`. So what I would do is spam ctrl+s to re-save the file, which in turn triggers the rebuild/compile process and outputs a """new""" file in my dist directory.

Either way, this method of developing any type of program is far from ideal. Sometimes everything works fine for an hour or two and then it randomly stops updating the script, other times it's buggy from the get go. On Chromium it might be better but I haven't done any extensive testing for longer than 15 minutes, I don't really use Chrome.

**Comment by virtuallyunknown** [comment]
Hey @tophf I am sorry to bother you, just have a quick question if you don't mind.

Not sure if you saw my comment above, but essentially during development I am serving the user script from a local server and I automatically recompile/rebuild the script when changes to my source files are detected, so a new file is created which ViolentMonkey uses.

Well, I came up with an idea. Every script has a metadata block sitting on top of it, with `@version` key of particular interest. So what I did was introduce a step in my build process that essentially modifies the `@version` to the current UTC timestamp - `Date.now()`. In other words, every time my script changes, so does the version, this way the current version is never the same as the last.

Since then, I have the feeling the problem went away, but since this is occurring so randomly I can not be completely sure. Since I am not aware of VM internals I was just curious if you think all this, could there be any plausibility to this theory, or perhaps I am imagining things and the `@version` key has no effect on this?

**Comment by tophf** [comment]
I don't know.

**Comment by cyfung1031** [comment]
> ### Sequence of actions:
> 1. Alter a script while file tracking is turned on.
> 2. Press F5 to refresh page and it runs old version of the script.
> 
> ### Problem:
> Runs old version of the script no matter how many times I update the script. When I open the script in VM, it shows latest version. If I reboot FF, latest version of the script is run.
> 
> I am not to sure how to reproduce, this. I uninstalled VM and reinstalled scripts from archive and it works for a while as expected but then it stops working.
> 
> #### Devtools console contents:
> No errors
> 
> #### Environment:
> * OS: Windows 10
> * Browser: FIreFox Portable 111.0.1 (64-bit)
> * Violentmonkey Version: 2.14.0

This bug usually exists when you have created your own UserScript instead of downloading it from somewhere.
If that script is created in local, you have to toggle the Violentmonkey ON/OFF button to make the refresh.
If you alter the script that is downloaded from a website, the alter can automatically apply.

**Comment by cyfung1031** [comment]
@tophf 
For your follow-up. I don't know what exact steps can reproduce this bug.
* I am sure it is not just Firefox, but also Chromium-based.
* I am sure it is not just Windows, but also MacOS.
* I am sure this only happens when you create a UserScript locally instead of install from internet
* Such issue is not found in Tampermonkey
There should be some bugs inside the javascript coding of Violentmonkey.

## Video

https://github.com/violentmonkey/violentmonkey/assets/44498510/f155d83a-8250-4a08-8d61-688423ef0700

Brave | 1.58.127 Chromium: 117.0.5938.88 (Official Build) (arm64)
-- | --
Revision | ed4ee11d4f6add8e0885cfab17943837d3d426c1
OS | macOS Version 12.6.1 (Build 21G217)
JavaScript | V8 11.7.439.16



## Suggestions
I suggest two ways based on my founding to temporarily resolve this issue.

### Suggestion 1 - ON/OFF Violentmonkey for every save action.

<img src="https://user-images.githubusercontent.com/44498510/268985012-f84b9250-05f5-406c-96f5-384c30670c82.png">
just toggle this button for every save action. It should work perfectly.

### Suggestion 2 - Change Script Name
As the video suggested, script name changing can help. So every save action:
* Read the script name => "Script ABC"
* add random suffix to it => "Script ABC 1695260807858"
* Save File
* remove the random suffix => "Script ABC"
* Save File

**Comment by cyfung1031** [comment]
@tophf 

I found a way to reproduce the issue.

https://github.com/violentmonkey/violentmonkey/assets/44498510/58fada89-34fe-40f0-93da-07bf2a936fd5

**Comment by cyfung1031** [comment]
Extreme Case: 

Script name change could not work. The file update is completely ignored.

https://streamable.com/bwmfc2

If that url matching changes, then the script can be updated once.

**Comment by tophf** [comment]
I still can't reproduce it here. Try the [latest dev build](https://github.com/violentmonkey/violentmonkey/actions/workflows/ci.yml) which addressed some of the potential problems.

**Comment by tophf** [comment]
I finally encountered it in Chrome Canary! Gonna investigate...

**Comment by cyfung1031** [comment]
> I finally encountered it in Chrome Canary! Gonna investigate...

In  BETA v2.15.4, the bug still there but just with less possibility.
(previously once per 1.5 hours, now  once per 5~6 hours)

1. The script was downloaded from internet.
2. The script will be updated once when the toggle of that script is OFF then ON again.
3. The bug will disappear when the script name changed (so i cannot post video here for reference).

**Comment by tophf** [comment]
Well, I definitely fixed the reported scenarios, so that bug is gone. I'll try to reproduce the bug with an update and if I don't fix it soon then it should be reported separately, hopefully with a more reliable method of reproducing.

**Comment by Sv443** [comment]
I had this same issue with the latest release version. Since then I installed the Beta 2.15.5 and haven't had any more issues with the script not updating. I will post an update here should it reemerge.

**Comment by cyfung1031** [comment]
> I had this same issue with the latest release version. Since then I installed the Beta 2.15.5 and haven't had any more issues with the script not updating. I will post an update here should it reemerge.

Install [2.15.8](https://github.com/violentmonkey/violentmonkey/actions/runs/6433391117), all problems are gone.

**Comment by tophf** [comment]
Our beta is signed by Mozilla.

**Comment by Sv443** [comment]
> Our beta is signed by Mozilla. They do it very slowly though, so the latest currently is v2.15.7.

Got it, that would explain why I didn't find it in the releases. Thanks!

**Comment by Sv443** [comment]
> > I had this same issue with the latest release version. Since then I installed the Beta 2.15.5 and haven't had any more issues with the script not updating. I will post an update here should it reemerge.
> 
> Install [BETA v2.15.8](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.15.8), all problems are gone.

Sorry if I'm spamming this issue with unrelated problems but on v2.15.7 and v2.15.8 the GM.setValue storage doesn't persist and also a new instance of the userscript is installed on each source change. I went back to v2.15.5 which doesn't have these issues and seems to be stable enough at the moment.

**Comment by tophf** [comment]
v2.15.8 has fixed the storage problem.

**Comment by tophf** [comment]
If it doesn't for you, please provide the details/script.

**Comment by tophf** [comment]
Also make sure you actually run v2.15.8.

**Comment by cyfung1031** [comment]
> Our beta is signed by Mozilla. They do it very slowly though, so the latest currently is v2.15.7.

Hi, just be interested how to install BETA version to Firefox.

For chrome, I can find the BETA version in Chrome Store.
For Firefox, I cannot find this.

So just install the zip version downloaded from GitHub release page?
I tried to install it to the Firefox Stable but in vain.

Could you guide me the proper procedure that how to install BETA version in Firefox? Thanks.

**Comment by Sv443** [comment]
> If it doesn't for you, please provide the details/script.

I created an issue for it: #1927

**Comment by Sv443** [comment]
@cyfung1031 there's an xpi that gets added after a while to each release. It's currently only available until beta 2.15.7. Once you download it there should be a popup in the top right to install it.
