### ISSUE TITLE
[Feature] An option to disable Violentmonkey on current tab

### ISSUE THREAD

**Issue by JenieX** [violentmonkey/violentmonkey#1796]
**Motivation**
When comparing a website content with and without Violentmonkey enabled, you would need to manually switch it on/off globally. It would be a great solution to have an option that allows you to  switch Violentmonkey on/off per tab.

**Proposed Solution**
A second button next to the global switch on/off button. Maybe not by default, since it would confuse many users as there aren't tooltip info when you hover over the current buttons.

**Comment by tophf** [comment]
The popup UI isn't supposed to have many buttons at the top, so I don't think we'll add anything there, especially such a rarely used feature.

We can add `Reload tab (no scripts)` action:
1. a shortcut hotkey customizable in the extensions management page of the browser
2. an item in the context menu of the Violentmonkey icon in the browser toolbar
3. an item inside '...' menu button shown instead of `+` i.e. the menu will be `New script`, `Reload tab (no scripts)`

@gera2ld?

**Comment by JenieX** [comment]
> The popup UI isn't supposed to have many buttons at the top, so I don't think we'll add anything there, especially such a rarely used feature.
> 
> We can add `Reload tab (no scripts)` action:
> 
> 1. a shortcut hotkey customizable in the extensions management page of the browser
> 2. an item in the context menu of the Violentmonkey icon in the browser toolbar
> 3. an item inside '...' menu button shown instead of `+` i.e. the menu will be `New script`, `Reload tab (no scripts)`
> 
> @gera2ld?

I like the first one. 😄
