### ISSUE TITLE
[BUG] Script not loaded on YouTube

### ISSUE THREAD

**Issue by peng-devs** [violentmonkey/violentmonkey#1823]
### Sequence of actions: 
1. Add a random script with `@match https://www.youtube.com/watch?v=**` like:
```
// ==UserScript==
// @name   Test
// @match  https://www.youtube.com/watch?v=**
// @match  https://www.youtube.com/live/**
// @grant  none
// ==/UserScript==

window.alert('test')
```
2. Enter https://www.youtube.com
3. Click a random video

### Problem: 
The script won't be loaded unless the page is refreshed.

### Expected result:  
The script should be loaded.

#### Devtools console contents:
No errors

#### Environment:
- OS: Windows
- Browser: Firefox 113.0.1 
- Violentmonkey Version: 2.14.0

**Comment by tophf** [comment]
This is working correctly because the site is a SPA and it doesn't load the page from server on navigation, instead it fakes navigation and the page remains the same. The solution is to match the entire site and check the URL inside a navigation observer, see [this example](https://stackoverflow.com/questions/34077641/how-to-detect-page-navigation-on-youtube-and-modify-its-appearance-seamlessly/34100952).
