### ISSUE TITLE
[BUG] Installed Scripts List Desync

### ISSUE THREAD

**Issue by hl2guide** [violentmonkey/violentmonkey#1858]
### Sequence of actions: 
1. Open main extension window
2. Click "Installed Scripts"
3. Install any new script
4. Click "close" button to go back to main list
5. Extension is not listed until page is reloaded (`F5`)

### Problem: 
After adding a new script it does not  appear on main list until page is reloaded.

### Expected result:  
Item is listed.

#### Environment:
- OS: Windows 10
- Browser: Vivaldi 6.1.3035.204 (Stable channel) (64-bit)
- Violentmonkey Version: v2.15.0

**Comment by tophf** [comment]
This is working correctly and always worked like this in userscript managers like Tampermonkey/Greasemonkey because userscripts are executed when a page is loaded or reloaded.

Theoretically we could change that but 1) it won't be universal as many `document-start` scripts won't work when executed after the page has already loaded and 2) our automatic tab reload option for toggling of scripts works only in a self-evident case in the popup of a particular tab whereas in this case of installing a new script we would have to reload all tabs where this script runs. I don't think we should make such a change, but we can add an option in the script installer `[x] Run in matching pages without reloading them`.

@gera2ld?

**Comment by hl2guide** [comment]
@tophf Thanks for the detailed response.

If possible it would be nice to fix the "I added a new script, where is it?" problem for new users.

A setting would be useful 😊

**Comment by gera2ld** [comment]
I think it's okay to add it to the popup menu, but we shouldn't inject it before the page reloads.
I suggest not to make things too complicated.

**Comment by tophf** [comment]
Ah, now I see the bug is with the dashboard, it doesn't list the newly installed scripts.
