### ISSUE TITLE
[Feature] Possibly add `javaScript` option into `@inject-into`

### ISSUE THREAD

**Issue by Axotot1** [violentmonkey/violentmonkey#1912]
**Motivation**

I have an script (running in a website with strict CSP rules) that need user's info (in `window.user.xxxxx`) to fetch news and push them (by using `GM_notification`)
but I don't need any DOM access.

**Proposed Solution**

using TM in firefox, I can [define `// @sandbox JavaScript`](https://www.tampermonkey.net/documentation.php#meta:sandbox) to get JavaScript APIs access.

**Comment by tophf** [comment]
`window.user` is not a JavaScript API. It's a custom global variable, to access which the script should run either in the standard JS context (Violentmonkey calls it `page`) or use `window.wrappedJSObject.user` in the isolated context (Violentmonkey calls it `content`).

Tampermonkey's `sandbox` naming of the modes doesnt make any sense, they just seem arbitrary words with no meaning attached, which is why I'm reluctant to add the support of it. For example, DOM is always available in a userscript, so what does sandboxing of DOM mean? You though it means you don't need DOM, but actually it means that the script is injected via DOM. Bad naming. Anyway, we don't allow injection in another kind of isolated context named `userscript` in Firefox, because it's a Firefox-specific feature not available in other browsers. We will implement a different cross-browser API when it's implemented in ManifestV3.

If you only use Firefox, Violentmonkey already provides the necessary sandboxing via [@inject-into content](https://violentmonkey.github.io/posts/inject-into-context/):

```js
// ==UserScript==
// ..............
// @inject-into content
// ..............
// ==/UserScript==

let data = window.wrappedJSObject.user;
```
