### ISSUE TITLE
[Feature] may produce a new API `GM_changeMenuCommand` ?

### ISSUE THREAD

**Issue by helloworldSB** [violentmonkey/violentmonkey#1928]
**Motivation**

Some user-adjustable Boolean configurations require to use `GM_registerMenuCommand`.
After user click the Menu Command, script will change the Storage value, then **Re-register Menu Command**
In order to maintain the relative order, every Menu Command will be Re-register, it's very time-consuming.

**Probably Solution**
let `GM_registerMenuCommand`'s return type extends string to bring a ID, and add an API to change the Command Label and the Callback function.

**Comment by tophf** [comment]
We can extend [Tampermonkey's implementation](https://www.tampermonkey.net/documentation.php#api:GM_registerMenuCommand) and allow specifying options in the third parameter as `{ id: 'foo', title: 'tooltip', autoClose: false }` - I don't think we should add `accessKey` because it would conflict with our keyboard navigation, @gera2ld ?

Calling GM_registerMenuCommand with the same `id` in the options parameter will allow updating the item in-place.
GM_unregisterMenuCommand can be called either with the id or the caption as previously.

**Comment by gera2ld** [comment]
Sounds good.
If the provided id does not exist, we can create a menu item with the id.
