### ISSUE TITLE
[BUG] does not trigger on https://carelink.minimed.eu/app/linking when logging in

### ISSUE THREAD

**Issue by divinity76** [violentmonkey/violentmonkey#1947]
### Sequence of actions: 
1. install the script
```
// ==UserScript==
// @name        New script - minimed.eu
// @namespace   Violentmonkey Scripts
// @match       https://carelink.minimed.eu/app/linking
// @grant       none
// @version     1.0
// @author      -
// @description 10/30/2023, 9:53:04 PM
// ==/UserScript==

console.log("test");
```
2. log in on https://carelink.minimed.eu

### Problem: 
script does not run when logging in and being automatically redirected to https://carelink.minimed.eu/app/linking
-but- it does trigger when refreshing the page after logging in, for example F5
### Expected result:  
the script should run when logging in and being automatically redirected to https://carelink.minimed.eu/app/linking
#### Environment:
- OS: Windows 10
- Browser: Firefox 115.3.1esr (64-bit)
- Violentmonkey Version: 2.16.0

**Comment by tophf** [comment]
This is working correctly because the site is a SPA and it doesn't load the page from server on navigation, instead it fakes navigation and the page remains the same. The solution is to match the entire site and check the URL inside a navigation observer, see [this example](https://stackoverflow.com/questions/34077641/how-to-detect-page-navigation-on-youtube-and-modify-its-appearance-seamlessly/34100952) (it's for an extension but the same principle applies).
