### ISSUE TITLE
[Feature] Request to add two new features

### ISSUE THREAD

**Issue by Rusenche** [violentmonkey/violentmonkey#1995]
**Motivation**
 I have 25 scripts installed but there is no option to delete all scripts at once.

**Proposed Solution**
 Add a function to delete all scripts, because currently you have to manually delete each script one by one.

**Use Cases**
 When I want to delete all the scripts I have, your extension does not provide a button/option to delete all scripts at once.

Hello, happy holidays.

I suggest adding two functions in your extension.

1. Add a button/option to make it possible to delete all custom scripts. Currently, it is extremely inconvenient to delete each personal script one by one, because it is currently impossible to delete all of the number of scripts easily and at once.

2. In your very nice extension, I terribly miss a "Reset" button/function. Let's say some user didn't back up their settings beforehand, but made changes to your extension, but can't figure out what to change to return the default settings?!

I really miss the option to "Reset" the default settings. There is currently no such option. My only option to return all settings to default is to uninstall your extension. To go to the site to reinstall your extension and that way I will get your extension with default settings. I'm surprised there isn't such an option at all...

___________________________

Well, I can't edit the title anymore, but:

3. Add option for manual user language change. When the user's nationality is such that your extension does not have a translation in that language, then your extension automatically selects a default language of "English".

Add an opportunity for us users to choose a language close to us from the available languages, but to be able to choose a language ourselves.

Please consider adding these buttons/features.

**Comment by tophf** [comment]
Bulk delete was suggested multiple times, but we don't want to add a new button for such a rare feature in the main dashboard UI. There's a simple workaround anyway: press the Down arrow and Delete keys repeatedly.

Your justification for resetting the settings sounds plausible, so I guess we'll add `Reset settings` and `Remove all scripts` buttons inside the settings page. It'll be inside the `Maintenance` section under `Backup` and we'll also move the `Vacuum` button.

> manual user language change

We use the built-in localization API, which uses the browser language and doesn't allow changing the language. We don't have plans to switch to a different localization API, because it's too complicated for such an edge case.

**Comment by tophf** [comment]
I wrote "inside the settings page". It's not a menu. There will be no buttons in any menus.
