### ISSUE TITLE
[BUG] `JSON.parse` parsing error occurred in a specific website

### ISSUE THREAD

**Issue by F9y4ng** [violentmonkey/violentmonkey#2012]
### Sequence of actions: 
1. Create the following script _[1]_
2. Visit https://ww7.manganelo.tv/
3. `JSON.parse` method reports error

**script _[1]_**:
```js
// ==UserScript==
// @name        New script
// @namespace   Violentmonkey Scripts
// @match       *://*/*
// @grant       unsafeWindow
// @version     1.0
// @author      -
// @description 1/18/2024, 1:09:32 PM
// // @run-at   document-start
// ==/UserScript==

(function() {
  'use strict';
  console.log(1,JSON);
  console.log(2,JSON.stringify);
  console.log(3,JSON.parse);
})();
```

### Problem: 
![vm](https://github.com/violentmonkey/violentmonkey/assets/15855068/3d9148d0-281b-4cc4-9ccc-d13f62b8aa63)

### Expected result:  
Can get the correct JSON.parse method.

#### Environment:
- OS: Windows 10
- Browser: Chrome 120
- Violentmonkey Version: 2.18.0/2.17.1 BETA

**Comment by tophf** [comment]
This is working correctly. The site redefines this method and since the userscript is injected in the `page` context by default it uses the site's method.

Solutions/workarounds:
1. Use `@inject-into content` to run in the isolated JS world
2. Use `@run-at document-start` and instruct the user to enable `Synchronous page mode` option in Violentmonkey's settings -> advanced, and make a local copy of JSON at the start of the userscript.
3. Extract the original method via an anonymous iframe:

```js
const f = document.documentElement.appendChild(document.createElement('iframe'));
const {JSON} = f.contentWindow;
f.remove();
```

**Comment by F9y4ng** [comment]
- Solution 1 The script needs to be running in the page mode; 
- Solution 2 I tried this and it doesn't work on this site; 
- Solution 3 It's a temporary solution, but the script will report an error when it encounters a site with CSP when it's running on all sites.

I wonder if it would be better to provide a new API interface through VM extension to obtain the original methods (including window.console, window.JSON, etc.)?

**Comment by tophf** [comment]
1. You can access page mode via separate code in GM_addElement + communication via CustomEvent. 
2. This is because of uBlock Origin extension that patches JSON.parse
3. I haven't seen sites that prevent anonymous iframes. Anyway, GM_addElement should work here.

> new API interface

No, because it would be the same as an anonymous iframe with GM_addElement.
In the future JavaScript will have a built-in ShadowRealm API.

**Comment by F9y4ng** [comment]
> 1. You can access page mode via separate code in GM_addElement + communication via CustomEvent.
> 2. This is because of uBlock Origin extension that patches JSON.parse
> 3. I haven't seen sites that prevent anonymous iframes. Anyway, GM_addElement should work here.
> 
> > new API interface
> 
> No, because it would be the same as an anonymous iframe with GM_addElement. In the future JavaScript will have a built-in ShadowRealm API.

Thank you for your reply.

**Comment by tophf** [comment]
To clarify my 3rd suggestion:

```js
const f = GM_addElement('iframe');
const {JSON} = f.contentWindow;
f.remove();
```

**Comment by F9y4ng** [comment]
hi @tophf 

Under Firefox 135.0 (64-bit), if the VM injection mode becomes `content`, an error will occur, and the error will be reported as `can't access dead object`. This means that `f.remove()` causes the above error, which is normal in chrome and also in TM. 

For example, if you visit github.com, you will get the above error when use `JSON.parse("AAA....")`.
