### ISSUE TITLE
[BUG]  not sure if this a bug, but `installed script` will empty for 2-5 minutes to show all the scripts.

### ISSUE THREAD

**Issue by shinji-ikari** [violentmonkey/violentmonkey#2053]
try the keyword `slow` `installed script` `script`. and no such kind of issue.
is it only me get this bug? is this a bug?
### Sequence of actions: 
1.run Firefox, click the violent monkey icon on tool bar--`settings/control panel`--click `installed script`--empty for 2-5 minutes then scripts show up one by one.
during the time, on the left shows `installed scripts` , after loading it shows `(49) installed scripts)

2.once it loaded , next time it will show immediately. but after restart the firefox, it still empty for 2-5 minutes.

### Expected result:  
hope even it needs time to load the scripts. hope there a warn or hint says `it's loading scripts`. not totally empty and feeling like i haven't install script or i lost all the scripts. it really kind of scare me....

and, is there a way to open a new tab to edit the scripts when in `settings/control`?
for now, in `settings/control panel`,  click the script name will go into edit directly, i need to reopen the `settings/control panel` to check other things.  and i didn't find any option about `open new tab to edit`.  am i miss something?

also, when i'm in Tab A, click the violentmonkey icon on tool bar --click the script ` </>` to open script edit. when close it it back to the `settings/control panel` , can it back to the Tab A, not the `settings/control panel`?

#### Environment:
- OS: Windows 7
- Browser: firefox 115.8.0esr (64) 
- Violentmonkey Version: 2.18.0

**Comment by tophf** [comment]
Do you use `sync` in settings of Violentmonkey? Sounds like your browser removes all the scripts after exiting then uses `sync` to download them from a network server. In that case it's a bug in Firefox. Try uninstalling Violentmonkey and install it again after restarting the browser. Also try making a new browser profile. Don't forget to export the script first in Violentmonkey settings.

> open a new tab to edit the scripts when in settings/control

You can right-click the tab and duplicate it:
![image](https://github.com/violentmonkey/violentmonkey/assets/1310400/f472a7cd-0aa3-4c21-9f6b-cdc613ff55f4)

> also, when i'm in Tab A, click the violentmonkey icon on tool bar --click the script  </> to open script edit. when close it it back to the settings/control panel , can it back to the Tab A, not the settings/control panel?

If you used the "Close" button in the editor it always returns to the script list in the same tab. If you used the browser to close the tab, the problem is unclear. Please don't report multiple unrelated problems in one issue, make a new report with more info and a screen recording.
