### ISSUE TITLE
Difference between @exclude and @exclude-match?

### ISSUE THREAD

**Issue by pstein** [violentmonkey/violentmonkey#2087]
I am sconfused. It does not become clear what the difference is between @exclude and
@exclude-match.

Could you give me an example what the difference is between e.g.

`// @exclude   http://*.foobar.com/some*/path/*`

and

`// @exclude-match   http://*.foobar.com/some*/path/*`

Thank you

**Comment by tophf** [comment]
Same difference as between `@include` and `@match`. An include/exclude like `https://*.google.com/*` will also match `https://foo.com/.google.com/blabla`. With matches each part of the pattern is required as `scheme://host/path` and even though `path` can be empty it's still explicitly specified due to the presence of the last `/`, which means we can ensure the pattern matches only the intended hosts.
