### ISSUE TITLE
[Feature] AI-powered pre-installation security review of scripts

### ISSUE THREAD

**Issue by nileshtrivedi** [violentmonkey/violentmonkey#2148]
**Motivation**
I am an experienced web developer and web user but despite being aware of ViolentMonkey, I never used it. I like the idea of userscripts in theory, but running unaudited code from anonymous developers with access to my session cookies seemed a bit scary.

However, lately I have started using ViolentMonkey because language models like Claude-3.5 made it easier for me to write/review/maintain userscripts.

**Proposed Solution**
Allow user to bring their language model access keys (such as with OpenRouter) and use it to perform a security review before a script from an external source like GreasyFork/OpenUserJS is installed. 

**Use Cases**
Gain confidence in third-party scripts before they are installed.

**Comment by tophf** [comment]
An AI review isn't trustworthy either, so I'm not interested in providing a feature that gives a false sense of security. Note that chrome extensions in the web store aren't trustworthy either in general, because the review is perfunctory and is performed on the minified code and not the source code. The same problem affects native apps/packages.

**Comment by tophf** [comment]
BTW, I also share the same concern and my solution was to globally forbid access to my account-specific sites for all extensions via [runtime_blocked_hosts policy](https://support.google.com/chrome/a/answer/9867568?hl=en) which can be configured for any Chromium-based browser except Opera, which weirdly doesn't support any policies. The only exception I make is uBlock Origin as well as extensions that I manually inspected (I load this exact version as an unpacked extension).

**Comment by nileshtrivedi** [comment]
@tophf But doesn't this policy apply per-extension (so for all scripts enabled in ViolentMonkey) rather than per-userscript? As far as I understand, the only way to restrict domain-level permissions per-userscript is by modifying their `@grant`s (which would break updates).

> An AI review isn't trustworthy either, so I'm not interested in providing a feature that gives a false sense of security

Fair enough. Although I do think LLMs can be reasonably good at flagging basic things like whether this code tries to read any stored data such as cookies, or sends it to an external URL. But I understand that this (and its failure modes) needs to be better researched and understood before implementing something like this. 👍

**Comment by tophf** [comment]
> rather than per-userscript

Well, I don't allow userscript extensions on my account sites, so indeed this idea is not helpful here.

A simpler solution for this kind of threat might be to add two per-script options in Violentmonkey:
* `[ ] run in blacklisted sites`
* `[ ] connect to blacklisted sites`
so that the user can add their sensitive sites to the global blacklist option in Violentmonkey and make an exception for a trusted script.

**Comment by tophf** [comment]
Or maybe just a global option below the blacklist `[x] disallow network requests to the blacklisted sites`.

**Comment by nileshtrivedi** [comment]
Yeah, those would be helpful.

**Comment by tophf** [comment]
Implemented in [beta](https://github.com/violentmonkey/violentmonkey/releases/).
