### ISSUE TITLE
 @require or @resource isn't refreshing

### ISSUE THREAD

**Issue by KParthSingh** [violentmonkey/violentmonkey#2162]
I recently started developing a user script, but I'm encountering an issue where data or cache (like @require or resources) isn't refreshing. I've tried reinstalling both the script and Violentmonkey multiple times.  I've tried reinstalling the script and Violent Monkey multiple times, and even created a new browser profile. The new changes only work on the fresh profile, but not on my main browser profile. How can I completely wipe out Violentmonkey's data?

**Comment by tophf** [comment]
Without seeing your code I can only guess it's a problem I've recently fixed in [beta](https://github.com/violentmonkey/violentmonkey/releases).

> How can I completely wipe out Violentmonkey's data?

Export the data in Violentmonkey settings, import the data back. If it doesn't help, export the data in Violentmonkey settings, uninstall Violentmonkey, install Violentmonkey, import the data back.

**Comment by KParthSingh** [comment]
uh beta version does not help.

**Comment by tophf** [comment]
These dependencies are external, so they are cached. This is the intentional behavior to avoid overloading the servers, otherwise they may ban the user's IP automatically for a long time.

The correct method of managing dependencies in general to ensure the correct version is used is to specify the version (or the tag or commit hash) like you do for https://greasyfork.org/scripts/408009-togbk/code/toGBK.js?version=832799 in all the other URLs.

**Comment by tophf** [comment]
Actually you already pinned three of your dependencies to a specific version, which will be used instead of the latest version:
* https://greasyfork.org/scripts/408009-togbk/code/toGBK.js?version=832799 - via 832799
* https://update.greasyfork.org/scripts/484066/1356008/EngineListForSearchEngineJumpPlus.js - via 1356008
* https://update.greasyfork.org/scripts/484072/1307338/RulesForSearchEngineJumpPlus.js - via 1307338

**Comment by KParthSingh** [comment]
Ooh. Thanks
