### ISSUE TITLE
Version 2.8.9 requires access to the clipboard - Why did you do that?

### ISSUE THREAD

**Issue by led9** [violentmonkey/violentmonkey#218]
Why do you need my clipboard, author, you decided to steal my passwords or what?

**Comment by led9** [comment]
I DON'T have firefox = WHY you need MY clipboard?
what kind of solution is this, can firefox  users send you data of their bank cards, and from users of other browsers you will not demand it?

**Comment by gera2ld** [comment]
First, there is a function called `GM_setClipboard` to be used in userscripts, hope you know that, to write to clipboard.
Second, the permission required (`clipboardWrite`) is to write to clipboard, not to read, which is exactly what `GM_setClipboard` does. **Even with the currently required permissions, nothing can be read from the clipboard.**

On Chrome, the extension can write to clipboard in the background no matter whether this permission is required. But on Firefox it must be required, otherwise `GM_setClipboard` fails. So I added this permission to make it work on both browsers. More details can be found [here](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Interact_with_the_clipboard).

I think you can just uninstall the extension to keep yourself safe from me.
And I hate the word "*steal*" from a user without knowing anything about what I am doing.
