### ISSUE TITLE
Violentmonkey not working with Synchtube userscript

### ISSUE THREAD

**Issue by KingThunder** [violentmonkey/violentmonkey#274]
### What is the problem?
Can't play videos with Synchtube userscript with Violentmonkey, works on Tampermonkey.
This only don't work with Google Drive videos, that need the userscript, youtube videos don't need it.
### How to reproduce it?
1. Install Userscript https://synchtu.be/google_drive_userscript
2. Find a Synchtube with Google Drive video

### What is the expected result?
To work.
### What is the actual result?
Not working.
### Environment
- Browser: Google Chrome, Firefox
- Browser version: Google Chrome 62.0.3202.89 (64-bit), Firefox 56.0.2 (64-bit)
- Violentmonkey version: 2.8.17
- OS: Windows 7 x64

**Comment by gera2ld** [comment]
The issue is about the script itself. It detects whether you are using Tampermonkey, and if not, it tries to work as if in Greasemonkey v3 in Firefox, which will certainly fail in Violentmonkey.

Here is the magic code in this script:
```js
    if (isRunningTampermonkey()) {
        unsafeWindow.getGoogleDriveMetadata = getVideoInfo;
    } else {
        debug('Using non-TM polling workaround');
        unsafeWindow.getGoogleDriveMetadata = exportFunction(
                getGoogleDriveMetadata_GM, unsafeWindow);
        setupGDPoll();
    }
```

So you should either turn to use Tampermonkey or file a issue to the script author.
