### ISSUE TITLE
Handy Image Configuration

### ISSUE THREAD

**Issue by gabri25ele** [violentmonkey/violentmonkey#294]
After install Handy Image https://sleazyfork.org/it/scripts/109-handy-image
With violentmonkey if I click on "Handy Image Configuration", it don't open anything (Configuration panel).

https://s18.postimg.org/55o2m572x/Immagine2.png

Why?
With tampermonkey it works normally.

**Comment by gera2ld** [comment]
Because the script requires the new `GM` object from Greasemonkey v4.
It detects APIs with `typeof GM.setValue`, leading to a fatal error because `GM` does not exist yet in Violentmonkey. (should be `GM && typeof GM.setValue`)
I think you need to file a issue to the script author.

BTW, Violentmonkey may implement `GM.*` APIs in the future but not yet.

**Comment by gabri25ele** [comment]
now it works :)
Yeeeeeaaaaahhhhhhh!
