### ISSUE TITLE
Does not work on sites with native methods polluted

### ISSUE THREAD

**Issue by sn260591** [violentmonkey/violentmonkey#295]
### What is the problem?
Violentmonkey does not work on these sites, even if security.csp.enable set to false:
[https://chan.sankakucomplex.com](https://chan.sankakucomplex.com)
[https://e621.net](https://e621.net)
[https://rule34.xxx/index.php?page=post&s=list](https://rule34.xxx/index.php?page=post&s=list)
(all links are NSFW)

### How to reproduce it?
Install the script:
```
// ==UserScript==
// @name _TEST_
// @namespace _TEST_
// @match *://*/*
// @grant none
// @noframes
// ==/UserScript==
unsafeWindow.console.log("_TEST_");
```

### What is the expected result?
A message will be displayed in the console.

### What is the actual result?
Nothing happens.

### Environment
- Browser: firefox
- Browser version: 57
- Violentmonkey version: 2.8.20
- OS: windows 7

**Comment by gera2ld** [comment]
In short, the websites has overridden some native methods, leading to some fatal errors. 

Violentmonkey needs to be run in the the same context as the web page itself. So if the web page breaks the basic equipments, Violentmonkey is broken too. For example, <https://e621.net/> has overridden `Array.prototype.toJSON`, as a result, all messages with the background are broken in Violentmonkey. I will try to fix this issue here, but such problems can hardly be 100% fixed.

**Comment by sn260591** [comment]
You can try to find the solution in the Greasemonkey code - this addon has no problems on these sites.

**Comment by Martii** [comment]
@gera2ld 
Don't know if this will help your situation but this popped into my head when I read this issue.

Ref:
* https://developer.mozilla.org/docs/Web/JavaScript/Reference/Operators/super
* https://stackoverflow.com/questions/11854958/how-to-call-a-parent-method-from-child-class-in-javascript

**Comment by gera2ld** [comment]
@sn260591 They don't work the same way. I don't think Greasemonkey can keep its old way working in the future. The fix is in progress and will be committed soon.
@Martii Thanks but they have nothing to do with this issue.
