### ISSUE TITLE
Scripts aren't working properly.

### ISSUE THREAD

**Issue by ranonn** [violentmonkey/violentmonkey#313]
### **What is the problem?**
Recently my scripts don't work properly, most of time they don't load into page. If I keep refreshing the page a few times there is a small chance to make them load but again if I refresh the page there is a high chance to break it.
Example of script : https://github.com/ccd0/4chan-x

### **Environment**
- Browser:  Firefox
- Browser version: v57.0.2 (x64)
- Violentmonkey version: v2.8.22
- OS: Windows 8.1

**Comment by Remu-rin** [comment]
Only on 4chan? Do you use uBlock Origin?
If both is yes, probably related to this filters update https://github.com/uBlockOrigin/uAssets/commit/43eb4648ba1126a58c933177da00154d469536dd
Fixed with https://github.com/uBlockOrigin/uAssets/commit/7242595e422318522dc37d3165dda034d43904c9 as far as I can tell. Force refresh in uBO (purge cache and update).
Though I don't know if it's even normal that first filter breaks Violentmonkey on a site.

**Comment by ranonn** [comment]
@Remu-rin Oh yeah, indeed it was a problem caused by ublock
My filters were outdated for 4 days and I didn't had the fix(looks like the fix was pushed 3 days ago) but now seems like everything is fine. Thanks.
