### ISSUE TITLE
[suggestion] add a menu entry to whitelist (add to user @excludes) the current site

### ISSUE THREAD

**Issue by elypter** [violentmonkey/violentmonkey#322]
many userscripts run on multiple or all websites but sometimes cause problems so you want to be able to disable the userscript on that site. currently you have to switch it off completely and you have to do this each time you visit that page. there is also the cumbersome way to go to the settings tab of the userscript and add an exclude but this isnt practical for the normal webbrowsing flow either. if you could just have a submenu for each userscript which contains: "ignore url", "ignore file", "ignore subdomain" and "ignore domain" that would make generic userscripts a lot easier to use

**Comment by B00ze64** [comment]
That sounds like a useful addition. I don't have to exclude sites very often but it happens, and right now it is several clicks away to get there (open dashboard, edit script, change to properties, click in exclude list, scroll down to last entry, enter the site). If this gets added I would like it to add *://website rather than only the protocol currently in use (I was unable to make a rule for both HTTP/HTTPS like I could do in Grease Monkey, so I have to use *://website; if there is a way then I would like the UI to add rules that target both HTTP/HTTPS with a single rule). Best Regards,

**Comment by tophf** [comment]
Closing in favor of #367.
