### ISSUE TITLE
add Browser Sync

### ISSUE THREAD

**Issue by Artlant** [violentmonkey/violentmonkey#342]
You have different types of synchronization. But why not Browser Sync?
It is available for Chromium / Chrome and this is most browsers. Why their various caveats?

**Comment by gera2ld** [comment]
Because they are not implemented on all browsers supported by Violentmonkey and not designed for sync large data like used by Violentmonkey.

For example, Chrome and Firefox has browser.storage.sync / chrome.storage.sync, I guess that's what you mean by *Browser Sync*, but they are not designed to sync large data like scripts. They are used for storing settings, up to 100KB, according to [the document](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/sync).
In other browsers like Maxthon, there is no such APIs.

Another important reason is, we cannot sync data between different browsers with third party services, e.g. sync scripts on Chrome with those on Firefox.

**Comment by Artlant** [comment]
@gera2ld 
> In other browsers like Maxthon, there is no such APIs.

yes it's really hard to decide. BUT!

I have now tested Tampermonkey and there, with the new installation of Chromium, scripts and their settings are loaded.

![screenshot from 2018-02-07 10-59-26](https://user-images.githubusercontent.com/13064767/35907649-3604b49c-0bf7-11e8-9801-a14d846d921f.png)

I believe that the settings of most scripts can fit in 100KB (compress).
And the scripts themselves reload the links.

I think this is a good solution. Because the **violentmonkey** positions itself as an alternative **Tampermonkey**. And borrowing their advantages in your project is logical.

I'm sorry if I demand a lot. I like your project. But his current meager opportunities make him a weak competitor to Tampermonkey.

Regards,
Raingart

**Comment by affan2021shaikh** [comment]
The full scripts don't have to be synced. Only the URLs and settings, correct? And many compression algorithms could still be used.

**Comment by tophf** [comment]
Compression can only help with very small scripts as the limits in this API are quite low. Lots of people would complain why some or many of their scripts can't be sync'd. It just doesn't make sense to use something that was never designed for this use case when we already have several sync providers that work. I also don't see browser.sync being used by Tampermonkey anymore. The only thing that might make sense is to sync the settings but then again it would only help with WebDAV credentials.

**Comment by affan2021shaikh** [comment]
Understandable.
