### ISSUE TITLE
Can't access custom window's property if there is granted GM_setValue from web console

### ISSUE THREAD

**Issue by T1mL3arn** [violentmonkey/violentmonkey#379]
### What is the problem?
Cannot access custom window's property if there is GM_setValue in @grant meta. During the development is sometimes needed to access script methods from browser's web console for purpose of testing of these methods.
### How to reproduce it?
1. Create new script
```js
// ==UserScript==
// @name Bug window access
// @match https://example.org/*
// @version 0.1
// @run-at document-start
// @grant GM_setValue
// ==/UserScript==//

window['Test'] = 'passed';
```
2. Go to [https://example.org](https://example.org) and open web console in your browser(F12 for Firefox)
3. Type `Test` and press `Enter`
### What is the expected result?
There should be text `"passed"` in the console's output
### What is the actual result?
```js
ReferenceError: Test is not defined[Подробнее] debugger eval code:1:1
```
### Environment
- OS: Win7 Ultimate
- Violentmonkey version: 2.8.30
- Tested in Firefox 59.0.1 and Opera 51.0.2830.55

### Some notes
Without `// @grant GM_setValue` all works fine - console shows string `"passed"`. Seems this problem happens for any `// @grant GM_` like `GM_xmlhttpRequest` or `GM_deleteValue`.

**Comment by gera2ld** [comment]
This is by design. Please use `unsafeWindow` instead of `window`.

If no `@grant` is specified, the script will run directly in the page context, sharing `window` with page scripts.
If any `GM_*` function is granted, the script will run in a wrapped context with special APIs provided, in which `window` is something like a sandbox, and `unsafeWindow` is the `window` for page scripts.
