### ISSUE TITLE
Custom CSS preset for Dark Mode (Check reply #5!)

### ISSUE THREAD

**Issue by ghost** [violentmonkey/violentmonkey#456]
I want to use this instead of TamperMonkey, but what holds me back is the bright white interface. I put dark modes on everything.

I do notice there is a section for Custom CSS, which will easily let me change the main background and font, but when it comes to changing the editor there's just SO many things to change to make everything legible.

Has anyone done a dark theme for ViolentMonkey using this? If so, where can I get it? And would you consider adding it as a dropdown preset people can select when using the extension?

**Comment by T1mL3arn** [comment]
> but when it comes to changing the editor there's just SO many things to change to make everything legible.

According to VM's doc, you can change VM css, but not the code editor. Although the editor based on Codemirror and supports themes. Here is a [theme demo](https://codemirror.net/demo/theme.html). At this moment, you can
1. change editor's css here https://github.com/violentmonkey/violentmonkey/blob/9e672d5590aea144840681b6f2ce0c267d57fc13/src/common/ui/code.vue#L46 and compile extension for yourself ¯\\\_(ツ)_/¯ .
2. use stylish extension (I don't know if it has access to other extensions' pages)
3. fork and implement theme selector and pull-request it

**Comment by Aidolii** [comment]
Thank you for the code editor CSS.

When I first wrote this issue, my Stylus extension was able to affect Violentmonkey, but Chromium has since disallowed extensions affecting other extensions' pages, so now I have the reverse of the issue I had before, where the code editor is dark but everything else isn't.

It would certainly be nice for a dark theme to be added.

**Comment by wjtk4444** [comment]
> I do notice there is a section for Custom CSS, which will easily let me change the main background and font

@Aidolii Would you mind sharing your style? I tried tinkering with it a bit, but it looks completely unreadable no matter what I do.

--

And about the code editor style

> At this moment, you can
> 1
> 2
> 3
> 4
5. Pick any of these: https://github.com/codemirror/CodeMirror/tree/master/theme, global replace `-stylename` with `-eclipse` and paste the edited contents to custom css section in Violentmonkey's settings.

Dirty hack, but a pretty low-effort one which is why I prefer it over the other 4 options (second is technically the same, assuming that stylus allows modifying other extensions' pages). I hope that one day Violentmonkey will get a proper normal / dark theme option as well as style selector for code editor, but I also understand that it's a low priority feature.

**Comment by SuperOP535** [comment]
Replacing with -themename won't be enough for all themes, for example I wanted to use darcula theme and it has a .darcula selector. Simply replace everything `themename` with eclipse.

The easiest way is to for example go to https://raw.githubusercontent.com/codemirror/CodeMirror/master/theme/darcula.css then paste `document.body.textContent.replace(/darcula/g, 'eclipse');` in JS console and paste the output to violentmonkey custom css input.

I'll make a dark theme for Violentmonkey soon and put the link here.

**Comment by SuperOP535** [comment]
@wjtk4444 Enjoy: https://github.com/SuperOP535/Violentmonkey-Theme

**Comment by Aidolii** [comment]
This is great! Thank you.

**Comment by tophf** [comment]
It's time to implement a simple built-in dark theme that would activate on [prefers-color-scheme: dark](https://caniuse.com/#search=prefers-color-scheme) automatically in new browsers when the OS and the browser are using the dark mode.

Also there can be a checkbox in the options so it would force the dark theme in older browsers:
```js
if ('darkTheme' in localStorage) {
  for (const el of document.querySelectorAll('link[media*="prefers-color-scheme: dark"]')) {
    el.media = 'screen';
  }
}
```
