### ISSUE TITLE
Violetmonkey in Chrome Web Store.

### ISSUE THREAD

**Issue by Piter432** [violentmonkey/violentmonkey#5]
Hi,

Can you upload your extension to Chrome Web Store? Yeah, I know there's already an extension to manage userscripts, but your extension is visually and functionally better than Tampermonkey.

Oh, by the way: I currently use Chrome, but it's possible to install your extension to Chrome.

I don't say that you must upload your extension to CWS. It's just a question :)

**Comment by tiansh** [comment]
Since os0x/NinjaKit seems to be discontinued, and derjanb/tampermonkey do not public source code for years. I hope there is an opensource GreaseMonkey-like extension on Chrome and Safari. Currently, only installation from the store is allowed on Chrome. So I hope violentmonkey may release Chrome or Safari versions. Thanks.

**Comment by gera2ld** [comment]
Now it's published in Chrome Web Store.

[Click here!](https://chrome.google.com/webstore/detail/violent-monkey/jinjaccalgkegednnccohejagnlnfdag)

**Comment by tiansh** [comment]
Got it and works fine. Than you.
BTW, the description of the extension still say `Userscript support for Opera.` in the Chrome web store.
