### ISSUE TITLE
no update found if `@version` does not exist

### ISSUE THREAD

**Issue by divinity76** [violentmonkey/violentmonkey#511]
### What is the problem?
the "check for updates" button always say "no update found" for scrips installed from file:// URI's.

### How to reproduce it?
1. make a script in C:\foo.js
2. install script from the uri file:///C:/foo.js
3. change the script in C:\foo.js
4. press the "check for updates" button

### What is the expected result?
the script is updated.

### What is the actual result?
"No update found."

### Environment
- Browser: Google Chrome
- Browser version:  Version 72.0.3626.96 (Official Build) (64-bit)
Google Chrome is up to date (2019-02-10)
- Violentmonkey version: 2.10.1
- OS: Windows 7 Ultimate SP1 X64

**Comment by divinity76** [comment]
err, after some investigation, turns out this only happens if the script does not have a @version tag..
not sure if this is a bug or intended behavior then, but IMO, if @version metadata is absent, the version detection *should* fall back to a full byte comparison of the source, instead of assuming that the code is unchanged (as seem to be the case right now)

**Comment by gera2ld** [comment]
This is by design. I will update the documentation later.

Only if `@version` exists, the script will update automatically. Otherwise scripts without `@version` will always be reinstalled, causing side effects like unexpected increase of installation times.

In your case, either reinstall the script manually or develop it like [this](https://violentmonkey.github.io/2017/03/14/How-to-edit-scripts-with-your-favorite-editor/).

**Comment by divinity76** [comment]
oh i see, thanks for explaining.
