### ISSUE TITLE
[Feature request] Edit published scripts with your favorite editor

### ISSUE THREAD

**Issue by akaleeroy** [violentmonkey/violentmonkey#516]
### What is the problem?

If you have published your script to someplace like GreasyFork then you can't edit in your favorite editor anymore. Because it's not installed locally and changing the `@updateURL` to serve from  `localhost` doesn't work.

### How to reproduce it?
1. Publish script to GreasyFork
2. Install from GreasyFork
3. Now I can't debug it locally

### What is the expected result?

At least it should accept an override of the `@updateURL` from Script settings > Custom metadata > Update URL: `http://localhost:8080/test.user.js`

### What is the actual result?

I can't live update a published userscript and work on it from the local machine. I have to disable it and install another instance for the duration of debugging.

### Environment
- Browser: Google Chrome
- Browser version: Chrome 72
- Violentmonkey version: Violentmonkey v2.10.1
- OS: Windows 7 x64

**Comment by gera2ld** [comment]
You need to install it from a local file so that Violentmonkey knows where to check updates from.

You don't need to disable it and install another instance since scripts with identical `@name` and `@namespace` will be regarded as the same. `@updateURL` won't be changed to the local URL because local URLs are ignored by design.

So all you need is to reinstall the script from a local file. I don't get it why you want to override `@updateURL`.

**Comment by akaleeroy** [comment]
I didn't understand how it behaved under-the-hood. It's already a good workflow, that's all I need, closing the issue, thank you for your help! 

Maybe put a section in [How to edit scripts with your favorite editor? - Violentmonkey](https://violentmonkey.github.io/2017/03/14/How-to-edit-scripts-with-your-favorite-editor/) letting people know doing the above is possible & safe.
