### ISSUE TITLE
Wrong language of userscript name and description

### ISSUE THREAD

**Issue by mikhaelkh** [violentmonkey/violentmonkey#527]
### What is the problem?
Wrong language of userscript name and description.

### How to reproduce it?
1. Add the following languages in browser settings:
- `English (United States)` (Chromium is displayed in this language)
- `English`
- `Russian`
2. Add [Direct links out](https://greasyfork.org/en/scripts/15857-direct-links-out) to Violentmonkey

### What is the expected result?
Name and description are in English

### What is the actual result?
Name and description are in Russian

### Environment
- Browser: Chromium 
- Browser version: 72.0.3626.121 (64-bit)
- Violentmonkey version: v2.10.3
- OS: Windows 10 v1607 x64

**Comment by gera2ld** [comment]
This is the desired behavior.

The script that you mentioned has meta below:
``` js
// @name        Direct links out
// @name:ru     Прямые ссылки наружу
```
Suppose `en-US, ru` is set in your `navigator.languages`.
Violentmonkey will look for `@name:en-US`, `@name:ru` in order to find a localized name. If none is found, it falls back to the default name `@name`.

In your case, `@name:ru` is found first, so name is in Russian.
Note that `@name` without a locale code is supposed to be the default one, not necessarily the one in English.
