### ISSUE TITLE
Sync with local file doesn't work in Chrome

### ISSUE THREAD

**Issue by john-cj** [violentmonkey/violentmonkey#582]
### What is the problem?

The "easy way" from the "[How to edit scripts with your favorite editor?](https://violentmonkey.github.io/2017/03/14/How-to-edit-scripts-with-your-favorite-editor/#install-a-local-script)" article doesn't work for me on Chrome.

### How to reproduce it?
1. Open `chrome://extensions/` and enable `Allow access to file URLs`.
2. Drag `test.user.js` from `C:\Users\John\Desktop\Foo` into Violentmonkey dashboard. Contents:

   ```js
   // ==UserScript==
   // @name Test
   // @namespace Violentmonkey Scripts
   // @grant none
   // ==/UserScript==
   
   console.log('Foo');
   ```

3. Make sure that "Allow update" check box at "Settings" tab is enabled.
4. Click "Confirm installation" and then "Close" button.
5. Open any page and see the `Foo` message in Chrome console.
6. Then, open file with your editor (Sublime Text and Notepad2 in my case) and change message to `Bar`. Despite the file was changed, this change will not happen inside Violentmonkey. Simply saying, the sync doesn't happen.
7. Additionally, I have tried to click these "round arrows" as shown in this image, but it doesn't help:

   ![vm](https://user-images.githubusercontent.com/18004961/60251523-57321e80-98d1-11e9-9f1c-48fa8df16ea9.png)

### What is the expected result?

After the 6th step, the script should be immediately and automatically changed inside Violentmonkey. It doesn't happen.

### What is the actual result?

You will have the old version of the script, i.e. with `Foo` message instead of `Bar`.

### Environment
- Browser: Chrome
- Browser version: 75.0.3770.100
- Violentmonkey version: 2.10.5
- OS: Windows 7 (32-bit)

**Comment by gera2ld** [comment]
This is the expected behavior.

Local scripts won't update by clicking the "round arrows" because they are supposed to be available only at development time.

All you need is to check **track local file** and **keep the confirmation page open**. Then you can just edit your script and it will be synced to Violentmonkey.

![image](https://user-images.githubusercontent.com/3139113/60267954-e8c77d80-991d-11e9-9d6c-e20a7d7cc618.png)
![image](https://user-images.githubusercontent.com/3139113/60267969-ef55f500-991d-11e9-9551-9b09d53e9f50.png)

**Comment by john-cj** [comment]
Thanks. But what about the scripts which are already installed? When I open the "edit" window of such script, there is no "Options" button.

**Comment by gera2ld** [comment]
@john-cj Just reinstall it from local.

**Comment by john-cj** [comment]
I just found another way, described at Stack Overflow:

* https://stackoverflow.com/a/55568502
* https://stackoverflow.com/a/55568568

**Step 1.** Create the following local file:

```js
// ==UserScript==
// @name    Test
// @match   *://*/*
// @grant   none
// ==/UserScript==

console.log('Foo');
```

**Step 2.** Create the following script in Tampermonkey/Violentmonkey dashboard (and of course, adjust the path as you need it):

```js
// ==UserScript==
// @name    Test
// @match   *://*/*
// @grant   none
// @require file:///C:/Users/YourName/Desktop/Userscripts/test.user.js
// ==/UserScript==
```

**Step 3.** That's all (almost). Now, if you edit the local file somehow, the changes will be automatically reflected in the browser. You don't need to copy, paste, or drag anything.

It seems that Violentmonkey cannot currently handle it in a complete automatic way: some manual work is necessary. You will need to go to "edit" window, make some fake change (i.e. to do some change and then undo it) and then resave the script.

**Comment by gera2ld** [comment]
> To reflect the changes in the browser, you will need to go to "edit" window, make some fake changes there (i.e. do some change and then undo it) and then resave it.

Violentmonkey caches resources that are required by a user script.

I don't like the way to require a local file, for several reasons.

1. It requires extra changes to your script, and those changes are dirty because they should not exist when it is published.
1. I always think that local files should not be required in a user script. It might bring up security issues, for example, by loading a user's private script accidentally. As a user I don't want to install any userscript that may read my local files.
1. A user script should be environment free, which means it should work after file syncing, or switching to another browser or system. But requiring a local file breaks it.

I think the Violentmonkey way is simple enough, you just need to drag the local file into browser, and click "Confirm" to install it. Done!
While the confirmation window is open, changes to your local file will be updated in Violentmonkey. And you don't have to make any dirty changes to your script.

**Comment by john-cj** [comment]
I see, thanks for explanation :-)
