### ISSUE TITLE
Does using IndexedDB and cloud sync permanently delete all userscripts when clearing Firefox site data?

### ISSUE THREAD

**Issue by lorenzos** [violentmonkey/violentmonkey#594]
Hi. Some days ago I cleared Firefox's cache, offline and site data [with the standard way to do that](https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox). I noticed too late that all my userscripts were gone, and unfortunately I had already used Firefox on all my devices, so Violentmonkey "synced" the empty data with Google Drive everywhere.

Is this the intended behavior? Isn't it too "dangerous"? I think clearing cache, offline and site data is a very normal thing to do, isn't it? I found no way to recover my userscripts, other than the `storage.js.migrated` files in profile's extensions data (which is from 4 months ago, before IndexedDB, but still better than nothing).

:sob:

**Comment by gera2ld** [comment]
There might be something wrong since the first sync between a new profile and a remote store should be a merging. 😢 

See also #590 . 
Since v2.11.1, you can restore your scripts from the recycle bin in 7 days, if they are removed from the dashboard unexpectedly, or *synced* to empty.

Hope you can find them back from another device.

**Comment by lorenzos** [comment]
> There might be something wrong since the first sync between a new profile and a remote store should be a merging.

Mmmh, I don't think it started as a "new profile". Settings persisted (I mean, the three checkboxes in "General", the fact that Google Drive sync was enabled, etc), only scripts disappeared. I didn't remove everything from my profile, just cache and what Firefox calls "site data", which I guess it's IndexedDB and local storage.

> See also #590 

I did, but I don't think it's related...

> Since v2.11.1, you can restore your scripts from the recycle bin in 7 days, if they are removed from the dashboard unexpectedly, or _synced_ to empty.

On my office PC (where I am right now) and on my phone, the recycle bin is empty.

> Hope you can find them back from another device.

I'll check my personal laptop tonight, where I have two chances (Win/Ubuntu dual boot). Scripts disappeared there too, but I didn't knew about the recycle bin. Anyway, turned out there's not so much missing in the March migrated storage, probably I'll need just a couple of hours to re-write the missing code.

That said, I'd like to reiterate the question: is this the "intended" behavior? Aside from bin, or sync issues, I mean, does clearing up IndexedDB delete userscripts too, by design? If yes, what about an option to disable auto-sync, so I can upload or download scripts from Google Drive (or from the other services) with distinct buttons? For example, uBlock Origin (which I think uses Mozilla cloud, don't ask me how) does this way, where you have a button to upload, one to download, and another to download and merge with current.

Thanks a lot for the quick reply.

**Comment by gera2ld** [comment]
> Is this the "intended" behavior?

If settings persist and scripts are gone, they are thought to be removed and will be synced to the remote. So the sync process is intended.

But I don't think it's the expected behavior for Firefox to clear all extension storage.
Violentmonkey stores data with `browser.storage`, which is recommended to store extension related data. As the document says [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage), data should be preserved:

> Although this API is similar to Window.localStorage it is recommended that you don't use Window.localStorage in the extension code to store extension-related data. Firefox will clear data stored by extensions using the localStorage API in various scenarios where users clear their browsing history and data for privacy reasons, while data saved using the storage.local API will be correctly persisted in these scenarios.

Nevertheless, data could still be lost sometimes (#264).

> what about an option to disable auto-sync, so I can upload or download scripts from Google Drive (or from the other services) with distinct buttons?

I think it's a good idea to work this way with the cloud, much more reliable.

**Comment by tophf** [comment]
Since Violentmonkey doesn't use IndexedDB (nor any other DOM storage), there's nothing we can do here.
