### ISSUE TITLE
Scripts don't run on sites with CSP like github.com

### ISSUE THREAD

**Issue by ivan** [violentmonkey/violentmonkey#60]
Violentmonkey scripts don't run on github.com, which has a restrictive [CSP (Content Security Policy)](https://developer.mozilla.org/en-US/docs/Web/Security/CSP) set up.

[stylish-chrome had a related problem](https://github.com/JasonBarnabe/stylish-chrome/issues/16) that one user solved by stripping the CSP headers from the response.  Perhaps instead of stripping the header, Violentmonkey could somehow add itself to list of allowed sources?  Not sure if this is possible, though.

**Comment by gera2ld** [comment]
The JavaScript injection problem should be fixed in violentmonkey/violentmonkey@ef56db9 ,  and the CSS injection problem is fixed in violentmonkey/violentmonkey@2c8cae0 but not released yet, so what's you problem exactly? Which versions of Violentmonkey and browser are you using?

There is a known issue to this solution: you cannot inject scripts or CSS or eval scripts in your code. Maybe I should add an option to strip the CSP header to remove the limitation aggressively.

**Comment by ivan** [comment]
Ah, sorry, you are right, this is specific to the kind of injection I was doing:

```
// ==UserScript==
// @name		Fix GitHub fonts - use the configured sans-serif font
// @namespace	githubfont
// @include		*://www.github.com/*
// @version     1
// @grant none
// ==/UserScript==

var styles = `
body { font-family: sans-serif !important; }
`;
var newSS = document.createElement('link');
newSS.rel = 'stylesheet';
newSS.href = 'data:text/css,' + escape(styles);
document.getElementsByTagName("head")[0].appendChild(newSS);
```

I was using Chrome 51 with violentmonkey 33d260451e221d58c1d3ad655a5f673cc2038da6.  I'll go upgrade and use `GM_addStyle`.  I didn't notice that commit, sorry.  And thanks for implementing this!

**Comment by ivan** [comment]
Oh, duh, I didn't notice it because it was on the dev branch :-)
