### ISSUE TITLE
Automation URL ?

### ISSUE THREAD

**Issue by Bumbadawg** [violentmonkey/violentmonkey#676]
Hi,
using Firefox, as you know we can't keep track of local files. 
But what i'm doing is :
1 - using a localhost server to make a grabbable URL for FF, 
2 - edit with vim with autoCmd to start a FF page on :w
3 - on FF, click install confirm on the updated script and ^+w to close the tabs opened.

Here's what my alias looks like for those interested in doing so:
```bash
cd ~/soft/scripts/***
http-server -c-1 -a 127.0.0.1 >/dev/null &
vim '+normal Go' -c 'autocmd BufWritePost * !firefox localhost:8080/***.user.js && qdbus org.kde.KWin /KWin setCurrentDesktop 3' ***.user.js
```
NB: qdbus command is to change to Firefox virtual desktop.

**QUESTION:** is there a URL or a shortcuts to automate the install confirmation of a script ? So i don't have each update to click "confirm install" and close those tabs.

Thanks.

**Comment by gera2ld** [comment]
Not yet. The confirmation is required to make sure that the script is desired, otherwise some malicious script could be installed silently.
After confirming installation, if you keep the confirmation window open, it can track your updates to the file by fetching it every few seconds. So you don't have to open the file and confirm again and again. Does that meet your needs?

**Comment by Bumbadawg** [comment]
Right @gera2ld i didn't think about letting the tab opened to keep the updates going, thanks for the tip and the explanations.
