### ISSUE TITLE
discrepancies between Opera & Chrome versions

### ISSUE THREAD

**Issue by filbo** [violentmonkey/violentmonkey#72]
https://addons.opera.com/en/extensions/details/violent-monkey has version 2.5.1; JS contents are not minified

https://chrome.google.com/webstore/detail/violent-monkey/jinjaccalgkegednnccohejagnlnfdag has version 2.5.2; JS contents are minified

https://github.com/violentmonkey/violentmonkey source and logs currently describe version 2.5.1

Where does 2.5.2 come from, why is it built differently?

I've noticed this discrepancy in 1 or 2 prior releases.  Is it just a postprocessing step, take the Opera m.n.o release, repackage it for Chrome and name it m.n.(o+1) ?  Why minify one and not the other?

(Sorry about empty issue.  I hit enter in the subject line and it submitted!?!)

**Comment by gera2ld** [comment]
1. Why is Opera version unminified and Chrome version minified?

   In Opera Presto days, the scripts in extensions are required to leave unminified. This extension was developed for Opera first, so I kept using unminified versions for Opera. I am not sure whether this is still required.

1. What's the difference between minified vs. unminified version?

   The only difference between Opera version and Chrome version is a different environment variable on build:

   ```
   # Unminified version for Opera
   $ npm run build

   # Minified version for Chrome
   $ npm run build --production
   ```

1. Why is Chrome version prior?

   Because addons for Opera need to be reviewed manually and takes relatively long time to upgrade to a new version if bugs are found. So the Chrome version is always published first. If any bug is found, I can fix it at the first time. Normally it will be upgraded to Opera if it becomes stable.

   And to be honest, I personally use Chrome more often now. So I might have forgotten to upgrade the Opera version sometimes...

**Comment by filbo** [comment]
Thanks for the prompt & thorough reply!

But why is 2.5.2 on Chrome store, but no evidence of 2.5.2 in git here?  This means the difference for me is: I can see what's going on in Opera version, but can't diff it with Chrome version even if they're practically identical.  argghh.

I was using 2.5.2 on Opera for a while, switched back to 2.5.1 in case there was an actual browser-dependent difference in the builds; this didn't affect my results.

I was on Chrome for a while, now back on Opera (after *LONG* hiatus since Opera 12, with no builds on Linux).  I'm finding it to have better startup properties, though it's a bit rough around the edges.

About to paste in my big bug...

**Comment by gera2ld** [comment]
My fault, I forgot to push the latest code to the repo. Now it's there.
