### ISSUE TITLE
关于最新版在容器打开新标签页的几点疑问与功能需求

### ISSUE THREAD

**Issue by ivysrono** [violentmonkey/violentmonkey#859]
https://violentmonkey.github.io/api/gm/#gm_openintab
经测试，已经开启多少个容器，‘container’ 最大就能设到几，超过就无效了。一般为4。
需求如下：
1. 如何检测用户是否已经开启容器功能？能否通过 VM 开启？
2. 如何检测用户已经创建了几个容器？能否通过 VM 对容器增删改查？

**Comment by tophf** [comment]
Technically this can be implemented using [browser.contextualIdentities](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contextualIdentities).
It doesn't add a new permission so I guess Firefox won't disable VM on update.
![image](https://user-images.githubusercontent.com/1310400/74079826-d255d880-4a4d-11ea-9fbc-332b13e18b9c.png)

However I'm not sure we should be exposing this to userscripts as it would require modifying GM API much more than just adding a simple innocuous parameter in GM_openInTab as we do now.
@gera2ld?

**Comment by gera2ld** [comment]
According to [the document](https://extensionworkshop.com/documentation/develop/request-the-right-permissions/), `contextualIdentities` does not get alerted to users. But I'm not sure if Chrome will accept an unknown permission.

The `container` parameter seems to expose unexpect implementation details to users. I think it does not make sense because users cannot predict which container they will get by providing a number that they can get from nowhere.
I guess it's better to pass a container name instead of an internal ID, and we can create the container if it does not exist, without the necessity to expose more container APIs.

**Comment by ivysrono** [comment]
```
I guess it's better to pass a container name instead of an internal ID, and we can create the container if it does not exist, without the necessity to expose more container APIs.
```
Great.

**Comment by tophf** [comment]
Chrome silently ignores unknown permissions. It'll only show an error in the card on chrome://extensions page when "Collect errors" is enabled in extension details (this is the default for unpacked extensions).

As for the `container` parameter, I certainly don't think it should be a name because a name can be easily changed and localized into different languages. Also, it's not what the problem is about as far as I can tell: do we add an API to list the containers and their info to userscripts or not?

**Comment by gera2ld** [comment]
Ah I thought name was like a unique ID for containers but it turns out to be a display name and not required to be unique.
If this is the case, I think we'll have to provide something like `GM_listContainers`, exposing name and cookieStoreId. Otherwise the `container` parameter for `GM_openInTab` seems almost useless.

p.s. Maybe we'll have to provide more container APIs someday if containers become popular and supported by more browsers.

**Comment by tophf** [comment]
I thought the container id would be definitely useful to write personal userscripts. But you're right, we should avoid adding browser-specific things to GM API so should we remove the `container` parameter and just always open the new tab in the current `cookieStoreId`?

**Comment by tophf** [comment]
This is out of the scope of userscripts as we would have to bring in quite a sizable chunk of Firefox API. You can probably convert your userscript into an extension.
