### ISSUE TITLE
[feature request] Allow fetching from resource archive

### ISSUE THREAD

**Issue by twifty** [violentmonkey/violentmonkey#918]
Currently we can get external files using `@resource` and `GM_getResourceText`, this is great for simple text files, images... etc. It's not so great for fetching archives (zip, gzip, tarball), specifically files from within those archives. We have to start importing extra code to extract the files.

Would it be possible for violent monkey to handle the extraction for us? Perhaps with a new function like `GM_getResourceContent` or a second argument to the existing `GM_getResourceText`.

**Comment by tophf** [comment]
VM has a [built-in zip library](http://gildas-lormeau.github.io/zip.js/core-api.html) which can be utilized for extraction indeed but I'd like to see a realistic example of such a use case.

As for a gm function it seems unlikely so far as we shouldn't be unilaterally extending GM API for such a specialized use case. Try to get TM's author interested and if they implement it, we'll follow suit. Greasemonkey will be against the idea, most likely, as usual, but their stance being always negative doesn't really matter anymore.

As for naming, I suggest using something with a `Zip` in it because `Content` is really vague and generic.

```typescript
GM_getResourceFromZip(name: string, {
  path: string,
  as: ('text' | 'blob' | 'data'), // `data` is a data: URI
  onload: function(data),
})
```

Depending on the use case it might make sense to extract files from a zip URL during installation/update:
`@resource name url#zip=foo/bar/file.txt`

**Comment by twifty** [comment]
A use case would be something like:
```
// @resource https://www.mdbg.net/chinese/export/cedict/cedict_1_0_ts_utf-8_mdbg.txt.gz
```
which contains a single text file of the same name (less the .gz). The archive is a Chinese to English dictionary database. I think it's far more common for resources to be archived. If not for compression then for data integrity.

I like the idea of using the existing function, but I was thinking of passing the archived file path as the second arg rather than a function. Internally though, VM would have to detect the type of archive and use the correct library for extraction.

As for TM, I stay clear of closed source projects, especially those which can monitor all of my online activity.

**Comment by tophf** [comment]
We don't have a gzip library AFAIK so I'd say this is your responsibility to handle extraction.
@gera2ld, what do you think on this idea in general?

**Comment by tophf** [comment]
On second thought, if this issue is mainly about gzip, it actually doesn't make a lot of sense because browsers and servers already apply gzip compression to data e.g. the physical network transfer size of that big txt is only 3.6MB. Storing a compressed resource doesn't make a lot of sense either because reading from the local disk would be faster than waiting for the slow JS uncompression code.

In other words, I'm against this feature.

On a tangentially related note, we could use the supposedly superfast [Compression Streams](https://www.chromestatus.com/features/5855937971617792) in supported browsers (currently Chrome 80+) to store the data internally, not exposed as an API, of course. But this is something totally different, which I'd like to combine with restoring IndexedDB for cached resources at least in Chrome where it can't be disabled anyway.

**Comment by twifty** [comment]
The issue isn't about transfer sizes or storage mechanics. It's about convenience. Most publicly downloadable resources are archives. Why? I don't know, but I guess it has something to do with checksums and corruption.

I requested this feature because as it stands, we have to include/inject additional libraries to extract the required files. Or, as I have done, extract the file and host it on a platform like github. If VM already has a decompression tool built-in, it would make a lot more sense for VM to handle the extraction for us.

Infact, I'm going on a tangent here, I'd really like to see a VM style extension where I could just `require` npm style modules from a trusted source. It would make creating scripts a whole lot easier with a much smaller end product. One of the first things I do when looking at a GM/TM/VM script is look at its imports. While I can control what script I install, I cannot control what it imports. If whatever it pulls in one day becomes malicious, I have no way of knowing.

**Comment by tophf** [comment]
I'm still against this because this is still an edge case (for example I've never seen it and I've been using or seeing a lot of scripts over the last 10 years) and anyway with Compression Streams API being available at least in Chrome it can be already done by a userscript.

**Comment by twifty** [comment]
Fair enough

**Comment by tophf** [comment]
Closing since neither me nor @gera2ld were interested. As for resource integrity, we'll probably implement [TM's method](https://www.tampermonkey.net/documentation.php?ext=dhdg#_require) as their implementation seems reasonable and doable.
