### ISSUE TITLE
Use browser sync for downloaded scripts?

### ISSUE THREAD

**Issue by clement-escolano** [violentmonkey/violentmonkey#929]
### What is the problem?
There is currently no browser native sync support.

### What is the expected result?
I understand the rationale on the [FAQ](https://violentmonkey.github.io/faq/#why-are-third-party-sync-services-used-instead-of-native-ones) about not using native sync because the scripts are too big.

Would it be possible to sync only the scripts that are fetched from a remote location (so there is only a small amount of data used)? I think this is [how Tampermonkey are handling it](https://www.tampermonkey.net/faq.php#Q105).

I am willing to help and even work on a pull request for it, but I would like to know what do you think before working on it.

**Comment by tophf** [comment]
I have no opinion on that as I'm not using sync at all but any implementation will have to obey the [strict limits of the API](https://developer.chrome.com/extensions/storage#properties). Since they are so low an efficient approach would be to utilize our zip library to compress the data into a string then slice it in 8000 byte chunks.

**Comment by mattrossman** [comment]
I would really like this feature. I think zipping everything and chunking like that is a good idea, and for casual use 100 KB should be plenty to store the remote URLS and preferences. If the user requires more space than that, it could show a ⚠warning badge explaining that sync is paused and they need to either clear some data or switch to a third party option.

**Comment by tophf** [comment]
Merging into #1527 which has more ideas.
