### ISSUE TITLE
[Feature Request] Add Update button to Extension menu

### ISSUE THREAD

**Issue by n00b42** [violentmonkey/violentmonkey#946]
Currently, I use Violentmonkey for FF and an other userscript manager for Chrome.

Comparing them, the thing I miss most in ViolentMonkey is an "Update" (Scripts) button in the addon menu.

When I develop my userscript I tend to push it very often, requiring me to switch to the dashboard (opening possibly in a different container) to update, and then back to the page I want to test the script on.
In the other userscript manager it is as simple as clicking on the menu and pressing update without leaving the page. (it pushs notifications to inform about update success though)

Btw: Thanks fo the amazing work on this plugin, using it on a daily basis.

**Comment by tophf** [comment]
Violentmonkey does this differently and, arguably, in a more convenient fashion: you [edit the file in your favorite IDE](https://violentmonkey.github.io/posts/how-to-edit-scripts-with-your-favorite-editor/) and let the installation tab track the changes automatically so there's no need to press any buttons. It doesn't work in the current VM 2.12.7 due to changes in FF68+ but the next version will restore this feature.

Tampermonkey also has a similar mode (probably even more convenient) by allowing the scripts to use `@require` to a file:// URL where the actual full script is located.

So I don't understand the use case for that button in the popup menu.

**Comment by tophf** [comment]
Closing because we already have an alternative (preferred) method that will work again in Firefox in the upcoming release, you can [test it now](https://github.com/violentmonkey/violentmonkey/releases).
