### ISSUE TITLE
GM_registerMenuCommand does not work for userscripts in frames

### ISSUE THREAD

**Issue by sn260591** [violentmonkey/violentmonkey#983]
### How to reproduce it?
1. Install script
```
// ==UserScript==
// @name GM_registerMenuCommand test
// @match *://interactive-examples.mdn.mozilla.net/*
// @grant GM_registerMenuCommand
// ==/UserScript==

GM_registerMenuCommand("MenuCommand", () => console.log("test"));
```
2. Open [https://developer.mozilla.org/en-US/docs/Web/CSS/color](https://developer.mozilla.org/en-US/docs/Web/CSS/color)

### What is the expected result?
"MenuCommand" should display under "GM_registerMenuCommand test" in the popup.

### What is the actual result?
 "MenuCommand" is missing.

If open [https://interactive-examples.mdn.mozilla.net/pages/css/color.html](https://interactive-examples.mdn.mozilla.net/pages/css/color.html) directly, then "MenuCommand" is displayed.

### Environment
- Browser: Firefox
- Browser version: 75
- Violentmonkey version: 2.12.7

**Comment by tophf** [comment]
Well, we don't show them intentionally. Can you explain a realistic use case where you would actually need it?

**Comment by sn260591** [comment]
I use a script that switches the audio gain in youtube videos.

**Comment by tophf** [comment]
Okay, that sounds like a good use case, but I still don't see what we can or should do because the frame structure of the site may be deeply nested and complicated, there can be lots of iframes, so we can't realistically show a menu for each frame. We show only one script entry for all instances of a script (even if there are 10 frame instances) so if we show a registered item there - which frame will be called? All of them? The last active one? Both methods are really bad so we can't use them.

You can make your script run everywhere and register the menu item in the top-level document:

```js
if (window === top) {
  GM_registerMenuCommand('foo', () => {
    const el = document.activeElement;
    if (el && el.tagName === 'IFRAME') {
      el.contentWindow.postMessage(GM_info.script.name, '*');
    }
  });
} else {
  window.addEventListener('message', e => {
    if (e.data === GM_info.script.name) {
      // do something
    }
  })
}
```
